### PR TITLE
Fix group algorithm that was breaking database tests

### PR DESCRIPTION
**Pull request by connie**
This pull request tries to fix the breaking of the database tests and the subgraph isomorphism check between groups.  (DO NOT PULL UNTIL WORKING)

Summary of changes:
- Add 'make test-database' to RMG-Py travis build to ensure safety

### CODE REVIEW

**Comment by nickvandewiele** [comment]
In https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/graph.pyx#L415 we iterate over the edges of `vertex1` and search for the index of the neighboring vertex in `self.vertices`:
```python
        for vertex1, old_value in zip(self.vertices, old_values):
            ...
            for vertex2 in vertex1.edges: count += old_values[self.vertices.index(vertex2)]
```

In https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/base.py#L953

vertices are removed from `self.vertices` while the references in `vertex.edges` are not removed at the same time.
```python
            removedAtoms = []
            for label, atom in structure.getLabeledAtoms().iteritems():
                if label not in centers:
                    removedAtoms.append(atom)
                    structure.atoms.remove(atom)
```


This leads to the following error:
```
  File "/vagrant_data/Code/RMG-Py/rmgpy/data/base.py", line 856, in matchNodeToNode
    return self.matchNodeToStructure(node,nodeOther.item, atoms=nodeOther.item.getLabeledAtoms()) and self.matchNodeToStructure(nodeOther,node.item,atoms=node.item.getLabeledAtoms())
  File "/vagrant_data/Code/RMG-Py/rmgpy/data/base.py", line 961, in matchNodeToStructure
    result = structure.isSubgraphIsomorphic(group, initialMap)
  File "rmgpy/molecule/group.py", line 782, in rmgpy.molecule.group.Group.isSubgraphIsomorphic (build/pyrex/rmgpy/molecule/group.c:15922)
    def isSubgraphIsomorphic(self, other, initialMap=None):
  File "rmgpy/molecule/group.py", line 809, in rmgpy.molecule.group.Group.isSubgraphIsomorphic (build/pyrex/rmgpy/molecule/group.c:15811)
    return Graph.isSubgraphIsomorphic(self, other, initialMap)
  File "rmgpy/molecule/graph.pyx", line 474, in rmgpy.molecule.graph.Graph.isSubgraphIsomorphic (build/pyrex/rmgpy/molecule/graph.c:8759)
    return vf2.isSubgraphIsomorphic(self, other, initialMap)
  File "rmgpy/molecule/vf2.pyx", line 77, in rmgpy.molecule.vf2.VF2.isSubgraphIsomorphic (build/pyrex/rmgpy/molecule/vf2.c:1595)
    self.isomorphism(graph1, graph2, initialMapping, True, False)
  File "rmgpy/molecule/vf2.pyx", line 102, in rmgpy.molecule.vf2.VF2.isomorphism (build/pyrex/rmgpy/molecule/vf2.c:2019)
    graph1.sortVertices()
  File "rmgpy/molecule/graph.pyx", line 448, in rmgpy.molecule.graph.Graph.sortVertices (build/pyrex/rmgpy/molecule/graph.c:8130)
    self.updateConnectivityValues()
  File "rmgpy/molecule/graph.pyx", line 292, in rmgpy.molecule.graph.Graph.updateConnectivityValues (build/pyrex/rmgpy/molecule/graph.c:5768)
    connectivityValues = self.__update([len(vertex.edges) for vertex in self.vertices], 0)
  File "rmgpy/molecule/graph.pyx", line 417, in rmgpy.molecule.graph.Graph.__update (build/pyrex/rmgpy/molecule/graph.c:7689)
    for vertex2 in vertex1.edges: count += old_values[self.vertices.index(vertex2)]
ValueError: <GroupAtom ['Ss']> is not in list
```

**Comment by connie** [comment]
Interesting, I wonder why this function worked fine before.

**Comment by nickvandewiele** [comment]
In the previous implementation of the sorting algorithm (cf. below), we did not search for the index of the neighbor vertex `self.vertices.index(vertex2)`:

```cython
    cpdef updateConnectivityValues(self):
        """
        Update the connectivity values for each vertex in the graph. These are
        used to accelerate the isomorphism checking.
        """
        cdef Vertex vertex1, vertex2
        cdef short count
        
        for vertex1 in self.vertices:
            count = len(vertex1.edges)
            vertex1.connectivity1 = count
        for vertex1 in self.vertices:
            count = 0
            for vertex2 in vertex1.edges: count += vertex2.connectivity1
            vertex1.connectivity2 = count
        for vertex1 in self.vertices:
            count = 0
            for vertex2 in vertex1.edges: count += vertex2.connectivity2
            vertex1.connectivity3 = count
```

**Comment by nickvandewiele** [comment]
Possible solution strategies I see:

- Flag atoms that should not be considered in the isomorphism check rather than removing them.
The flag could be an attribute of Vertex that is set at runtime. 
The sorting algorithm will not crash anymore, but the isomorphism code of `vf2` will need to be updated.

- Fully remove/add atoms rather than only modifying `self.vertices`
There is `removeVertex` available which will update both vertices and edge. Adding the atoms and bond afterwards will require a bit more work.

- Updating the sorting algorithm such that we don't need to search the index of removed atoms

**Comment by rwest** [comment]
Fully removing (including the bonds) sounds dangerous as part of an isomorphism `matchNodeToStructure` check. We'd be modifying the graph that we're checking, so if the group definition of the Node we're checking against specifies the presence of a bond, which we just removed from the structure, then we'll get a false negative?  Though I haven't looked fully at the context to see if this would be a problem here, it just feels risky.

**Comment by connie** [comment]
I think I agree with Richard, go with option 3: Updating the sorting algorithm such that we don't need to search the index of removed atoms

**Comment by nickvandewiele** [comment]
I agree with strategy _2_ being a risky road. I tried strategy _1_ for the following reason:

The removal of the atoms leads to a graph in which vertex/edge references are temporarily out of order. The new sorting implementation did not do implement any risky behavior, it simply searched for an index of vertex in the graph's vertex list. Hence, imho it revealed a piece of code that could lead to trouble in the future.

That being said, I do introduce a new boolean attribute in Vertex, which is in principle something inherent to the algorithm, and not to the data structure.

**Comment by rwest** [comment]
Solution looks OK to me. Profiling data from Travis build suggests my last commit helped (though I've not repeated the test). All tests pass, so going to merge.

**Pull request merged**
