### PR TITLE
Add unit tests to chemkinTest

### PR DESCRIPTION
**Pull request by mliu49**
I started out trying to write tests for each untested line, but I realized that it wasn't really helping. A major untested part was writing chemkin files, so I added some additional checks to existing tests. The end result was only +6% coverage within chemkin.py. To increase coverage more, we need to test reading and writing the other kinetics formats besides Arrhenius and Chebyshev.

### CODE REVIEW

**Comment by KEHANG** [comment]
@mliu49 not sure what `mock` is doing here. Can you explain why we need add as a new RMG dependency?

**Comment by mliu49** [comment]
mock allows creating fake instances of python modules. In this case, mock is used to create a fake logging module to intercept calls to logging.warning. This allows unit testing that specific logging statements are actually created.

In this case, the unit tests I added aren't particularly important, but I had written them in my initial attempt to cover line-by-line. I quickly realized that that wasn't a particularly good way to go about it, but I kept the tests anyway.

If you don't think those tests are worth keeping, then I'm fine with not adding them. However, I think mock does have future value in unit testing.

**Comment by rwest** [comment]
I like it. But perhaps add a few docstrings or comments in the unit test to help others understand what on earth is going on?  To someone who's not worked with `mock` before, it's not particularly obvious.  And it might be something we want to replicate elsewhere.

**Comment by mliu49** [comment]
I will add more info about `mock` to the docstrings.

**Comment by KEHANG** [comment]
@mliu49 ready to merge?

**Pull request merged**
