### PR TITLE
Delete unzipped files at end of HR2D test

### PR DESCRIPTION
**Pull request by mjohnson541**

### CODE REVIEW

**Comment by mliu49** [comment]
When I run the test, I get changes to `arkane/data/CH2CHOOH/r0/IOfiles/r0.pes` and a new file `arkane/data/CH2CHOOH/r0/r0.out`.

**Comment by mjohnson541** [comment]
Should be fixed now.

**Comment by mliu49** [comment]
Could you add `external/Q2DTor` to .gitignore, and then rebase on master since this is more than 1 commit?

**Comment by mjohnson541** [comment]
Done

**Pull request merged**
