### PR TITLE
Fix bug in flux diagram script

### PR DESCRIPTION
**Pull request by nickvandewiele**
addresses https://github.com/ReactionMechanismGenerator/RMG-Py/issues/479

### CODE REVIEW

**Comment by nickvandewiele** [comment]
@KEHANG : could you review this PR and merge it into master if OK?

**Comment by nickvandewiele** [comment]
I guess Travis does not allow the temporary creation of files/folders and that's why it's crashing.

**Comment by nickvandewiele** [comment]
It's maybe also a good hint to check whether we can pipe the streams of the dot/png files produced by graphviz into mencoder.

**Comment by connie** [comment]
Closed by new PR https://github.com/ReactionMechanismGenerator/RMG-Py/pull/711

**Pull request closed without merging**
