### PR TITLE
Fix of checkForExistingSpecies for biaromatics according to issue#643

### PR DESCRIPTION
**Pull request by KEHANG**
This PR includes
- fix of checkForExistingSpecies for biaromatics according to [issue#643](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/643) where if the molecule has more than one aromatic rings and only some of them are kekulized, the checkForExistingSpecies will fail.By running generateResonanceIsomers in checkForExistingSpecies, it will create isomers with fully
kekulized version, which makes checkForExistingSpecies work again.

- a unittest of checkForExistingSpecies for biaromatics.

### CODE REVIEW

**Comment by nickvandewiele** [comment]
can you replace the under_score style variable name by camelCase?

**Comment by nickvandewiele** [comment]
Seeing this fix, makes me question why the method signature of `CERM.checkForExistingSpecies` contains a `Molecule` parameter instead of a `Species`, especially given the method name...

I understand why this fix works, but calling that very expensive method without reusing any of the results (the newly created species object is never returned/stored), is really a pity.

I wonder if the method could be called elsewhere such that its generated resonance isomers will reused?

**Comment by connie** [comment]
The reason we had to do this was because of faulty resonance isomer generation for aromatics (unidirectional). Which means for some cases you cannot find a particular isomer. But you can generate resonance isomers for it and get the more generalized form. This function using just molecules would work fine if the resonance isomer generation worked perfectly. I also wonder if we can have speed up and do this for only aromatics because as far as I know only the aromatics are affected.

**Comment by connie** [comment]
Also @kehang you should rebate this branch.

**Comment by rwest** [comment]
Yes, seems costly and I think this gets called a lot. At very least only do to cyclic species and only generate the aromatic isomer not all resonance isomers. 
As Connie says, better would be to have resonance forms reliably generated in the first place, but there can be very many and perhaps in the long run the whole aromatic/resonance thing needs rethinking. 

Another thought: Is a type of graph isomorphism possible that treats bond orders flexibly in such a way as to allow different resonance forms to appear isomorphic?

**Comment by connie** [comment]
I believe the graph isomorphism check between two graphs is very rigid/checks for exact bond/multiplicity/electronic structure.  I think it probably needs to stay that way for the purpose of generating reactions..  The flexible bond orders could potentially be applied to list checking molecule to species.molecule, or species to species?

**Comment by KEHANG** [comment]
@rwest I added a new commit which only generate aromatic isomers for cyclic species, so for normal molecules, the method `checkForExistingSpecies` is still the same. Can you review this PR?

**Pull request merged**
