### PR TITLE
Add CITATION.bib file to make citing RMG easier

### PR DESCRIPTION
**Pull request by JacksonBurns**
### Motivation or Problem
RMG-py provides a list of citations, but does not take advantage of the GitHub [Cite this Repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) feature which automatically provides BibTex files with appropriate citations to users.

### Description of Changes
This PR adds a single `CITATION.cff` file that is (hopefully) correctly formatted and accurate.

### Testing
After merging, GitHub will automatically detect the file and add a Cite this Repository button, and any formatting/accuracy issues will then be obvious.

### Reviewer Tips
The CITATION.cff file format is described [here](https://citation-file-format.github.io/assets/pdf/cff-specifications-1.0.0.pdf).

### CODE REVIEW

**Comment by yunsiechung** [comment]
I made a pull request (#2351) to add the RMG database paper ([doi:10.1021/acs.jcim.2c00965](https://pubs.acs.org/doi/10.1021/acs.jcim.2c00965)) to the "How to cite" section in the README.md file.  Will you add that to the `CITATION.cff` file?

**Comment by JacksonBurns** [comment]
Additional paper added. When pushed, it renders a button like this on the repository:
image
See it for yourself [here](https://github.com/JacksonBurns/mtepor).

**Comment by yunsiechung** [comment]
Looks good!
It looks like the branch is be behind the `main` branch. Could you rebase it with the latest `main` branch and push again?

**Comment by JacksonBurns** [comment]
Done!

**Comment by yunsiechung** [comment]
I think we usually rebase the branch with `main` and force-push the branch, so we don't have an additional commit like [1f182aa](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2346/commits/1f182aaec2c635204540a7ceea16e93e5cbd2806)`.

If you RMG's official git repo is called `official`, it will follow:
`git fetch official`
`git rebase official/main`
`git push -f official [name_of_the_branch_to_push]`

Will you undo your last commit (`git reset HEAD~1`) and follow the procedure above?
Also, the first two commits can be combined as one commit to minimize the number of commits.

**Comment by JacksonBurns** [comment]
Can you squash and merge instead? Seems cleaner than undoing a commit, combining two commits, and then rebasing.

**Comment by JacksonBurns** [comment]
Moved to #2357

**Pull request closed without merging**
