### PR TITLE
Adjust updating and resetting of react flags in execute

### LINKED ISSUE #1427: Model Looping Bug
In some RMG runs the iterator gets caught into a loop where it adds the same reactions to the edge over and over again:  

```
Generating kinetics for new reactions...
For reaction C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553) Ea raised from -4.7 to -4.7 kJ/mol.
Updating 0 modified unimolecular reaction networks (out of 4820)...


Summary of Secondary Model Edge Enlargement
---------------------------------
Added 0 new core species
Created 0 new edge species
Added 0 new core reactions
Created 2 new edge reactions
    C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553)
    C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553)

After model enlargement:
    The model core has 98 species and 1720 reactions
    The model edge has 3573 species and 9050 reactions

...

Generating kinetics for new reactions...
For reaction C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553) Ea raised from -4.7 to -4.7 kJ/mol.
Updating 0 modified unimolecular reaction networks (out of 4889)...


Summary of Secondary Model Edge Enlargement
---------------------------------
Added 0 new core species
Created 0 new edge species
Added 0 new core reactions
Created 2 new edge reactions
    C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553)
    C=[C]CC(1339) + buten1yl1(1340) <=> butyne1(2546) + butene1(553)

After model enlargement:
    The model core has 98 species and 1720 reactions
    The model edge has 3573 species and 9052 reactions
```

It's worth noting that if you go earlier in the log file other chemistry continues to be added while these reactions are re-added to the edge and that this has only been observed so far for pdep jobs.  

I was running propyl-methyl ether combustion with input file:  
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2198000/input.txt)

The truncated log file:  
[RMG.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2197996/RMG.log)

Reproducing this bug appears to be a bit difficult as it appears to depend on what database branch you use.  I ran the above on the MPether branch.

### PR DESCRIPTION
**Pull request by mliu49**
### Motivation or Problem
Fixes #1427. Models were entering into infinite loops of adding reactions. The cause was failing to properly reset react flags leading to repeatedly reacting species together.

### Description of Changes
The `updateReactionThresholdAndReactFlags` method was changed to always reset the react flags regardless of whether or not core species were added. Related changes were made to the `execute` method in order to update these arrays on every iteration, regardless of whether or not core species were added.

### Testing
Run `eg1` locally (the one in RMG-tests is different). It should now stop properly after reaching 29 core species.

### CODE REVIEW

**Comment by mliu49** [comment]
There were some significant changes in the sulfur test.

**Comment by alongd** [comment]
Yes, the changes to the sulfur test look significant. Wierd that that's the only one which was changed.

**Comment by alongd** [comment]
The EA job completed correctly on this branch and the rulestotraining -db branch

**Comment by mliu49** [comment]
We think that the changes in the sulfur test are likely because we are updating the filter on every iteration now, instead of only when core species are added. This could have caused RMG to react some species earlier, leading to different edge behavior. The end result was that S(12) was added to the core.

@mjohnson541 thinks that updating the filter every iteration is the preferred behavior, instead of basing it on core species addition. @alongd, let us know your thoughts about the sulfur test, and whether you think the changes are acceptable or if the input file may need to be adjusted.

**Comment by alongd** [comment]
A different sulfur model ran with only slight modifications on this branch, I think it's OK to merge

**Comment by mliu49** [comment]
@alongd or @mjohnson541, feel free to merge. I think this is ready.

**Pull request merged**
