### PR TITLE
New handling Molecule parsing from SMILES, InChI, etc.

### PR DESCRIPTION
**Pull request by connie**
This pull request is now on the official repository, for easy edits by multiple users.  Please refer to the previous pull request https://github.com/ReactionMechanismGenerator/RMG-Py/pull/435 for more details.

=====
# Summary:
This PR bundles three major, related improvements to the `rmgpy.molecule` package:

1. A refactoring of the identifier generation and parsing functionality of the molecule module
2. A new way of sorting atoms
3. A first attempt in creating an canonical (augmented) inchi for species with complex electronic structures.

## Identifier generation and parsing

A subpackage of the molecule package is created: `rmgpy.molecule.parser`. This package bundles modules related to the generation and parsing of molecule identifiers such as SMILES and InChI. This stuff was originally to be found in the `rmgpy.molecule.molecule` module. With different backends (rdkit, openbabel) and different identifiers (SMILES, SMARTS, InChI, InChI key, augmented inchi) this became quite large, hence the idea of moving it to its own sub-package.

## Sorting atoms

Prior to this PR, vertices were sorted based on a vertex connectivity value that calculated the connectivity of a vertex until the 3rd degree. This is rather limited, oftentimes leading to multiple equivalent sorting possibilities of atoms.

The new sorting algorithm implements Morgan's idea, by recursively updating the connectivity value of the vertices, until the number of distinct connectivity values is maximized.

Next, `molecule.sortAtoms()` uses not only the connectivity value of the vertex (`sortVertices`), but also its atom attributes like charge, radicalElectrons, lonePairs.

I believe this leads to a unique sorting order of atoms in contrast to the previous implementation.

## Canonical (augmented) inchi

Prior to this PR, the augmented inchi was an inchi with the total multiplicity of the molecule appended at the end.

E.g.:
the triplet biradical .C=C. was represented by:
`InChI=1/C2H2/c1-2/h1-2H/mult3`

Because backends are only able to convert the InChI to a graph, this lead to wrong graphs.

E.g.:`InChI=1/C2H2/c1-2/h1-2H/mult3` would be converted into ethyne (C#C) rather than the
biradical with the identical atom connectivity.

This PR tries to heuristically correct for those mistakes, e.g. by converting the triple bond into
a double bond, with neighboring radical atoms.

In addition, in some cases the multiplicity info is not enough to unambiguously reconstruct the 
graph from the augmented InChI, leading to errors downstream. Therefore, a new (optional) layer is created that indicate the atoms that bear unpaired electrons.

.C=C. might be represented by

`InChI=1/C2H2/c1-2/h1-2H/mult3/u1,2`

with `/u1,2` referring to the location of the unpaired electrons (atoms 1, and 2).

## Additional
Besides these 3 main features, I created some minor modifications:
- cache the InChI in the Molecule object
- a molecule hash and equality comparison method
- removing the identifier generation from the molecule constructor

### CODE REVIEW

**Comment by nickvandewiele** [comment]
worker script:

```python
#global imports
import os.path
import unittest
import logging

#local imports
from rmgpy.chemkin import loadSpeciesDictionary




def load(fpath):
    """Return a list of molecule objects."""
    speciesDict = loadSpeciesDictionary(fpath)
    spcList = speciesDict.values()
    molList = [spc.molecule[0] for spc in spcList]
    return molList

def loadJP10():
    working_dir = 'tests/JP-10/'
    fpath = working_dir+'mmc3.txt'
    assert os.path.isfile(fpath)
    return load(fpath)


def loadButanol():

    working_dir = 'tests/Butanol/'
    fpath = working_dir+'mmc3.txt'
    assert os.path.isfile(fpath)
    return load(fpath)


def read():
    spc_list = []

    jp_10 = loadJP10()
    spc_list.extend(jp_10)

    butanol = loadButanol()
    spc_list.extend(butanol)

    logging.info('Total no. of species: {}'.format(len(spc_list)))
    return spc_list

def test_toAugmentedInChI(mollist):
    N = 10
    for i in xrange(N):
        [mol.toAugmentedInChI() for mol in mollist]
    assert True

def main():
    mollist = read() 
    toAugmentedInChI(mollist)

if __name__ == '__main__':
    main()

```

Profiling script:
```python
#!/usr/bin/env python
# encoding: utf-8
# filename: profile.py

import pstats, cProfile

import pyximport
pyximport.install()

import scalability_molTest

cProfile.runctx("scalability_molTest.main()", globals(), locals(), "Profile.prof")

s = pstats.Stats("Profile.prof")
s.strip_dirs().sort_stats("time").print_stats()
```

Some profiling results:
```
         1359185 function calls (1359176 primitive calls) in 77.749 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    11614   26.254    0.002   46.135    0.004 parser.py:631(toRDKitMol)
   704052   15.287    0.000   15.287    0.000 {method 'index' of 'list' objects}
    10530    8.658    0.001    8.658    0.001 inchi.py:92(MolToInchiAndAuxInfo)
     1053    7.274    0.007   14.127    0.013 adjlist.py:160(fromOldAdjacencyList)
   177483    3.745    0.000    3.745    0.000 {method 'iteritems' of 'dict' objects}
    61297    1.368    0.000    1.368    0.000 {method 'strip' of 'str' objects}
     1053    1.358    0.001    6.881    0.007 {method 'generateResonanceIsomers' of 'rmgpy.species.Species' objects}
61438/61435    1.285    0.000    1.285    0.000 {len}
    10530    1.243    0.000   53.684    0.005 parser.py:715(toAugmentedInChI)
    44371    0.940    0.000    0.940    0.000 {method 'append' of 'list' objects}
    11614    0.849    0.000    0.849    0.000 {method 'sortAtoms' of 'rmgpy.molecule.molecule.Molecule' objects}
    10530    0.776    0.000   51.259    0.005 parser.py:675(toInChI)
    10530    0.737    0.000    9.645    0.001 inchi.py:125(MolToInchi)
    27240    0.580    0.000    0.580    0.000 {method 'partition' of 'str' objects}
        2    0.539    0.270   23.278   11.639 chemkin.py:683(loadSpeciesDictionary)
    10530    0.499    0.000    0.661    0.000 parser.py:700(createULayer)
    10530    0.478    0.000   54.162    0.005 {method 'toAugmentedInChI' of 'rmgpy.molecule.molecule.Molecule' objects}
    15879    0.441    0.000    0.441    0.000 {method 'updateCharge' of 'rmgpy.molecule.molecule.Atom' objects}
    14864    0.356    0.000    0.356    0.000 {method 'split' of 'str' objects}
    13811    0.344    0.000    0.344    0.000 {method 'search' of '_sre.SRE_Pattern' objects}
    14864    0.338    0.000    0.338    0.000 {method 'sort' of 'list' objects}
    14864    0.319    0.000    0.319    0.000 {method 'keys' of 'dict' objects}
    14670    0.316    0.000    0.316    0.000 {range}
    13811    0.304    0.000    0.304    0.000 {method 'replace' of 'str' objects}
    13796    0.298    0.000    0.298    0.000 {method 'items' of 'dict' objects}
     1053    0.295    0.000   15.072    0.014 adjlist.py:438(fromAdjacencyList)
    13811    0.290    0.000    0.290    0.000 {method 'upper' of 'str' objects}
     1053    0.276    0.000   15.348    0.015 {method 'fromAdjacencyList' of 'rmgpy.species.Species' objects}
    10530    0.266    0.000    0.266    0.000 parser.py:776(createMultiplicityLayer)
    10530    0.255    0.000    0.255    0.000 inchi.py:78(compose_aug_inchi)
    10530    0.250    0.000    0.250    0.000 {method 'find' of 'str' objects}
        1    0.246    0.246   54.408   54.408 scalability_molTest.py:61(writeInChITest)
     7600    0.162    0.000    0.162    0.000 {method 'join' of 'str' objects}
     2100    0.145    0.000    0.430    0.000 __init__.py:1602(debug)
       53    0.128    0.002    0.226    0.004 parser.py:435(fromRDKitMol)
     2101    0.095    0.000    0.142    0.000 __init__.py:1332(isEnabledFor)
     2100    0.094    0.000    0.236    0.000 __init__.py:1118(debug)
     3159    0.083    0.000    0.083    0.000 {method 'splitlines' of 'str' objects}
        2    0.073    0.037    0.073    0.037 {open}
     2100    0.068    0.000    0.068    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
     1053    0.056    0.000    0.056    0.000 model.py:70(__init__)
        2    0.052    0.026    0.052    0.026 {posix.stat}
     1053    0.051    0.000    0.088    0.000 re.py:226(_compile)
     2101    0.048    0.000    0.048    0.000 __init__.py:1318(getEffectiveLevel)
     1053    0.046    0.000    0.134    0.000 re.py:188(compile)
     1054    0.026    0.000    0.026    0.000 {method 'format' of 'str' objects}
     1053    0.024    0.000    0.024    0.000 {method 'pop' of 'list' objects}
     1063    0.024    0.000    0.024    0.000 {method 'get' of 'dict' objects}
     1051    0.022    0.000    0.022    0.000 {method 'extend' of 'list' objects}
       53    0.021    0.000    0.021    0.000 {method 'update' of 'rmgpy.molecule.molecule.Molecule' objects}
      833    0.020    0.000    0.020    0.000 {method 'addBond' of 'rmgpy.molecule.molecule.Molecule' objects}
```

**Comment by rwest** [comment]
From talking to @nickvandewiele this afternoon I came to understand that the atom numbering of where the unpaired electrons live in the augmented InChI (eg. with `/u1,2` meaning unpaired electrons on atoms 1 and 2), do not necessarily correspond to the numbering of the atoms in the InChI, but are determined by the RMG atom sorting. Drawbacks of this are that, (1) although much more reliable than before this PR changed the sorting algorithm, RMG's order is still not guaranteed canonical, and (2) it is different from InChI so that nobody else can use or interpret our augmented InChI's, and (3) if we ever change the sorting algorithm again we can't even trust our own augmented InChIs.

So I looked into how the ordering is done in the InChI algorithm.
The bad news: [it's complicated](http://depth-first.com/articles/2006/08/12/inchi-canonicalization-algorithm/) and would be a pain to re-implement.
The good news: if we're generating the InChI anyway, we can get the official InChI API to return the mapping to the original atom ordering in the Auxiliary Information! - see Fig 2A on P11 of the [InChI Technical Manual](http://www.inchi-trust.org/download/104/InChI_TechMan.pdf) . Via RDKit this is done using [`MolToInchiAndAuxInfo()`](http://www.rdkit.org/docs/api/rdkit.Chem.inchi-module.html#MolToInchiAndAuxInfo) and presumably (not checked) is not much slower than just getting the InChI.
Check the bits beginning with `N:` in the AuxInfo lines:
```python
In [6]: def test(smiles):
   ...:     m=Chem.MolFromSmiles(smiles)
   ...:     return Chem.MolToInch
Chem.MolToInchi            Chem.MolToInchiAndAuxInfo  
   ...:     return Chem.MolToInchiAndAuxInfo(m)
   ...: 

In [7]: test('OCCC')
Out[7]: 
('InChI=1S/C3H8O/c1-2-3-4/h4H,2-3H2,1H3',
 'AuxInfo=1/0/N:4,3,2,1/rA:4OCCC/rB:s1;s2;s3;/rC:;;;;')

In [8]: test('CCCO')
Out[8]: 
('InChI=1S/C3H8O/c1-2-3-4/h4H,2-3H2,1H3',
 'AuxInfo=1/0/N:1,2,3,4/rA:4CCCO/rB:s1;s2;s3;/rC:;;;;')
```

Although probably too slow for some of our sorting purposes, for cases when we are generating InChIs anyway, this ordering is guaranteed canonical and stable.

p.s. if we do a lot of InChI stuff and it turns out to be important *after we do profiling*, we may look into calling the IUPAC API directly rather than going via RDKit.

**Comment by nickvandewiele** [comment]
Very interesting @rwest !

I do suggest to implement this (if possible) in another PR. 

About the speed issue of InChI canonicalization:

Recently, a scalability study was conducted ([here] (http://www.slideshare.net/NextMoveSoftware/cinf-1-generating-canonical-identifiers-for-glycoproteins-and-other-chemically-modified-biopolymers) and some more comments [here] (https://nextmovesoftware.com/blog/2015/08/24/biopolymer-canonicalisation-scaling-between-toolkits/)) that showed that RDKit (2015) may not necessarily slower than the IUPAC API, on the contrary.

**Comment by rwest** [comment]
Oops. Sorry for breaking the build. I tested it locally, but must have failed to commit my changes properly or something. Will look at when back at my computer

**Pull request merged**
