### PR TITLE
fixups in `get_training_set` family method

### PR DESCRIPTION
**Pull request by davidfarinajr**
Some small fixups in the `get_training_set` method which is used for autogen tree method

1) make a deepcopy of the species to get the thermo.  This is needed to clear the atom labels on the molecule which can mess with getting thermo

2) parse out the metal from the entry

### CODE REVIEW

**Comment by Tingchenlee** [comment]
I think this PR fixed the errors of `KeyError: 'Node not found for atom {} in molecule <Molecule "O=CO.[Pt]"> in thermo database adsorptionPt111.'` in `Surface_Dissociation_vdW` family!
But I have another error in rmgpy.molecule.graph.Graph.get_edge `ValueError: The specified vertices are not connected by an edge in this graph` now...

**Review by rwest — APPROVED** [review]
This looks OK to me

**Comment by mjohnson541** [comment]
Might it be faster to grab the labels with get_all_labeled_atoms, then clear the atoms and then reapply them afterwards? 

On the larger families this already takes a while to run and this adds an extra deepcopy not just for every species in the dictionary, but for the reactants and products of every reaction in the training set.

**Comment by mjohnson541** [comment]
Just pushed a commit doing that.

**Comment by davidfarinajr** [comment]
> Might it be faster to grab the labels with get_all_labeled_atoms, then clear the atoms and then reapply them afterwards?
> 
> On the larger families this already takes a while to run and this adds an extra deepcopy not just for every species in the dictionary, but for the reactants and products of every reaction in the training set.

so something like this?
```
mol = species.molecule[0]
labeled_atoms = mol.get_all_labeled_atoms()
mol.clear_labeled_atoms()
species.generate_resononace_structures()

> Just pushed a commit doing that.

Thanks, looks good to me

**Review by rwest — COMMENTED** [review]
Can't see anything wrong

**Pull request merged**
