### PR TITLE
bug fix for qchem module, species with less than 3 vibrational modes

### PR DESCRIPTION
**Pull request by enochd**

### CODE REVIEW

**Comment by rwest** [comment]
This looks fine to me (not having a qchem file to check it against); but do we have any unit tests for this bit of code? Not crucial, but now might be a good time to add some (eg. one that would have failed before this commit)

**Comment by enochd** [comment]
Good idea. I'll add a few unittests, as I completely forgot about our loose policy to write unittests that accompany all changes.

**Comment by enochd** [comment]
Im not sure why these commits would have caused the make error?:

make: *** [eg1] Error 1
The command "make eg1" exited with 2.

**Comment by rwest** [comment]
I think the travis environment has changed. My PR which changes nothing but the documentation is also failing.

**Comment by rwest** [comment]
I have made a commit on master that makes RMG compatible with the latest version of `psutil`, which the Travis CI environment is now using. Please rebase this branch onto the latest master, and hopefully the unit tests will pass...

Something like:
```
git fetch official
git rebase official/master
git push -f github master
``` 
where `official` and `github` are whatever you have called your ReactionMechanismGenerator (formerly GreenGroup) and your personal remotes.

**Comment by rwest** [comment]
I split the code changes into #397 and added the documentation commits to #396. Thanks @enochd!

**Pull request closed without merging**
