### PR TITLE
Add licensing information to the README file

### PR DESCRIPTION
**Pull request by yunsiechung**
### Motivation or Problem
One of the reviewers of my manuscript asked us to add the licensing information to somewhere that is easier to find. So I added the licensing information to the README.md file, as well as the link to the resource and references and the disclaimer.

### Description of Changes
The 'License Information' and 'Disclaimer' parts are directly obtained from the file headers of RMG-Py. 
The 'Resources and References' part directs to the RMG-website resources page. I also added a line saying `Please at least cite our latest publication on Reaction Mechanism Generator v3.0 and other relevant publications when publishing the results using our software` to make sure that the RMG users cite some RMG-related publications.

Please let me know if anything should be changed or worded differently!

### Testing
N/A

### Reviewer Tips
N/A

### CODE REVIEW

**Comment by mliu49** [comment]
Thanks @yunsiechung! I think it may be easier to link the license file instead of copying the full text in the README. That would avoid adding another place to update when the copyright is updated.

Perhaps something like this:
```markdown
RMG is a free, open-source software package (distributed under the [MIT/X11 license](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/LICENSE.txt)).
```

**Comment by yunsiechung** [comment]
@mliu49 Thank you for the feedback! I made the change you suggested and force-pushed it.

**Review by mliu49 — APPROVED** [review]
Thanks, this looks good to me. I'm not sure why RMG-tests is failing though. @amarkpayne

**Comment by amarkpayne** [comment]
It looks like RMG-tests has failed for every PR we have merged in since fixing it in [this PR](https://github.com/ReactionMechanismGenerator/RMG-tests/pull/79). I'll go ahead an merge in this PR since it obviously has nothing to do with RMG-tests, but we should fix this (I'll open a separate issue)

**Comment by amarkpayne** [comment]
Thanks for the PR @yunsiechung and thanks @mliu49 for reviewing this!

**Pull request merged**
