### PR TITLE
Quotegen

### PR DESCRIPTION
**Pull request by cgrambow**
Replaces #1684

### CODE REVIEW

**Comment by mliu49** [comment]
Travis is encountering a weird error:
```
[libprotobuf FATAL google/protobuf/stubs/common.cc:86] This program was compiled against version 3.7.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.9.2).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.7.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.9.2).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/genfiles/tensorflow/core/framework/tensor_shape.pb.cc".)
```

**Comment by cgrambow** [comment]
I thought the error might be due to a tf version issue but I have the exact same version locally and I am not able to reproduce the error. Don't know what's going on.

**Comment by amarkpayne** [comment]
@cgrambow what is the status of this PR?

**Comment by cgrambow** [comment]
I have been trying all day to get new conda builds to work but there are conflicts when making the RMG environment and the conflict messages from Anaconda are utterly useless. I'm tempted to give up and remove this functionality from RMG.

**Comment by cgrambow** [comment]
I think the issue is some kind of conflict between chemprop and textgenrnn. Maybe the issues would go away if the quote generator were written in pytorch as well, but translating the textgenrnn code to pytorch is not a top priority right now. There exist some pretrained pytorch models that I could fine-tune on the quote data but the smallest, rapidly implementable model I can find is 500 MB large. Not very big in this day and age but perhaps too large if the quote generator ends up being the biggest part of RMG... What do you think?

**Comment by JacksonBurns** [comment]
This PR is attempting to merge into `master`, which is abandoned. Closing this PR as stale and deleting the branch.

If there are commits on this branch that should be merged into `main`, please restore the branch, cherry pick them, and open a new PR.

**Pull request closed without merging**
