### PR TITLE
Removing the excessive debug comment

### LINKED ISSUE #2050: Suggestion to delete a debug line in `chemkin.pyx`
[This line](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/7e7879b7fb9c46a406bc8feccc1c9a33bce16add/rmgpy/chemkin.pyx#L1119) is being printed too many times and out of context while debugging tests. See below. I suggest to remove it, unless there are objections.

image

### PR DESCRIPTION
**Pull request by MichaelGeuking**
### Motivation or Problem
fixes #2050. This PR fixes the issue that a comment while debugging is repeated excessive amounts of times

### Description of Changes
I commented out the the logging line

### CODE REVIEW

**Review by mjohnson541 — DISMISSED** [review]
Thanks! Can you delete the line rather than just comment it out and then rebase your branch on master?

**Comment by JacksonBurns** [comment]
@mjohnson541 this enormously complex PR should now be ready for review :sweat_smile:

**Comment by JacksonBurns** [comment]
Oops, didn't realize it was trying to merge into `master` instead of `main`. Changed base, re-rebased, and _now_ should be ready.

**Review by sevyharris — DISMISSED** [review]
Looks good! The only comment I have is that if we're going to delete this logging on line 1217, we should also delete the same thing on line 1220 to be consistent.

**Comment by JacksonBurns** [comment]
@sevyharris done! Will re-request a review.

**Review by hwpang — COMMENTED** [review]
Looks good to me. Can you squash or fix up the latter two commits into the first one, and rebase with main?

**Comment by JacksonBurns** [comment]
@hwpang done, thanks!

**Pull request merged**
