### PR TITLE
Log the species RMG crashes on if atomType doesn't exist

### PR DESCRIPTION
**Pull request by alongd**
Logging the species RMG crashes on when an unknown atomType is discovered. Important for debugging when modifying atom types, see issue #809.
For now I only saw a need to add this fix to molecule.py, and not to adjlist.py (where `getAtomType` is also being called).

### CODE REVIEW

**Comment by mliu49** [comment]
You should be able to do `from .atomtype import AtomTypeError`, then have `except AtomTypeError:` and `raise`.

Also, the resonance module frequently calls `updateAtomTypes()`, with the expectation that encountering an AtomTypeError indicates an infeasible resonance structure has been generated. It might be undesirable to have all of those species printed as well. Maybe you could add a boolean argument to indicate whether or not to print the species? Then we could update the calls from resonance.py later to turn off the logging.

**Comment by alongd** [comment]
Thanks @mliu49 , let me know if you have more comments

**Comment by rwest** [comment]
Based on max's comment it sounds like this is currently in a place where we don't always want logging. Could we move it further up the stack trace to somewhere where the error is always an error that's worth logging? (Rather than having to pass in extra arguments about whether we want logging or not). 
(This comment made without looking at the code, so treat accordingly)

**Comment by mliu49** [comment]
I think you need to modify molecule.pxd as well, since the module is cythonized. I can work with you on this tomorrow if you want.

**Comment by alongd** [comment]
I added a flag set with a default value for presenting the log info. If we want to call the func without logging, just send 0 in addition to self. Will that be OK, or do you think we still need to change?

**Comment by mliu49** [comment]
I pushed a commit so that we only catch an AtomTypeError, and we also print the adjacency list of the problematic molecule.

I think it is ok to default to printing the extra information, because usually it will be helpful for debugging. I think resonance structure generation is the only place where an AtomTypeError is acceptable.

**Comment by alongd** [comment]
Will add these commits into a more comprehensive PR.

**Pull request closed without merging**
