### PR TITLE
Add jupyter notebook to simulate and analyze superminimal & change docker instruction 

### PR DESCRIPTION
**Pull request by hwpang**
### Motivation or Problem
I add a Jupyter notebook to help the user to simulate and analyze the superminimal example as part of the RMG Training.

### Description of Changes
- A Jupyter notebook to simulate and analyze superminimal through pyrms.
- I modify the `.gitignore` to avoid ignoring the new jupyter notebook
- I modify the website instruction for users who want to use jupyter notebooks came with RMG docker. This is not just limited to the new Jupyter notebook, but for the more general use case of Jupyter notebooks in the `ipython` folder.

### Testing
- I downloaded the latest docker, ran the superminimal example, and tested this notebook. The notebook took around 5 min to run on a normal laptop (2.8 GHz Quad-Core Intel Core i7) for the first time due to (pre)compilation.

### CODE REVIEW

**Comment by xiaoruiDong** [comment]
I will try to run the notebook and see if I want to add any edits. Then we can merge it in. Thanks!

**Comment by hwpang** [comment]
@xiaoruiDong I'm working on updating the jupyter notebook, so please wait me for a bit! Thanks!

**Comment by hwpang** [comment]
@xiaoruiDong I just updated the notebook! 

For the "simulating RMG model" lecture, please use `simulation_flux_rop_superminimal_RMS.ipynb` notebook.
The other two notebooks are for the "Simulation and Sensitivity Analysis using RMS (Reaction Mechanism Simulator)" lecture. One of them contains many different ways to obtain sensitivities for the superminimal case using pyRMS, and the other uses different absolute tolerances and compare their IDTs.

The IDTs of superminimal isn't too sensitive to the absolute tolerance. The notebook is an example in case the user is curious about their own system.

**Comment by hwpang** [comment]
@xiaoruiDong @JacksonBurns The updates on the notebooks are done. Please feel free to review!

**Review by JacksonBurns — COMMENTED** [review]
The changes to the `.gitignore` and docs are good - thanks for figuring out how to run Jupyter in the docker container. This seems like a good way to advertise using RMG in general.

The jupyter notebooks look good and are easy to follow. I will defer to @xiaoruiDong on final approval since I cannot comment on the correctness of the content itself.

**Comment by hwpang** [comment]
This PR requires https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2431 to be merged first, so that the test results on forked branches can be reported correctly

**Review by JacksonBurns — COMMENTED** [review]
LGTM! Again, will defer to @xiaoruiDong for final approval.

**Comment by hwpang** [comment]
Just rebased. Gonna merge this now so that the documentation can be updated and the notebooks will be included in docker for tomorrow's RMG training.

**Pull request merged**
