### PR TITLE
generate edge seeds

### PR DESCRIPTION
**Pull request by mjohnson541**
A fundamental problem with using seed mechanisms to restart a run is that an input seed mechanism could be treated one of two ways
1) you don't react them -> you are missing lots of species from the edge that should be there
2) you react them -> you haven't had time to prune so you risk crashing your simulation or being forced to remove lots of edge species that might not have otherwise been pruned

Currently we only treat them as done in (1).  

@amarkpayne suggested that we just save the edge as well as core instead of having to manage all of this.  

This pull request generates an additional seed mechanism named name+"_edge" with an edge thermo library and an edge reaction library.  

Now when effectively restarting a run you can add the core seed mechanism as a seed mechanism and the edge seed mechanism as a reaction library, giving you the edge and core your original run ended with.

### CODE REVIEW

**Comment by mliu49** [comment]
What are the use cases of this "restart" method vs. restart files?

**Comment by mjohnson541** [comment]
This approach requires a tiny fraction of the runtime and memory required to save a restart file, but after some tests I believe this will give you the exact same core and edge (I though it might react species in the input file with the seed mechanism, but it doesn't appear to do this if the included species are in the seed mechanism).  So I think ideally we would phase out restart file generation in favor of this.  I haven't been able to think of any advantage of restart file generation over this yet.

**Comment by mjohnson541** [comment]
I just ran heptane-eg5 and did not get that error when starting with the created libraries.

**Comment by mjohnson541** [comment]
We should also note that we've resolved the case with eg1 in #1147 now.

**Comment by amarkpayne** [comment]
The issue for heptane-eg5 was solved by @mjohnson541 and @mliu49, and the fix will be included on a separate pull request. With the minimal example working with the fix suggested in #1147 this pull request should be ready to merge.

**Comment by KEHANG** [comment]
Did anyone check the RMG-tests result for this branch before merging: https://travis-ci.org/ReactionMechanismGenerator/RMG-tests/builds/265355211?utm_source=github_status&utm_medium=notification? It cannot even finish eg3 (the second example). Before this merge, we at least can finish eg6: https://travis-ci.org/ReactionMechanismGenerator/RMG-tests/builds/262807529?utm_source=github_status&utm_medium=notification

@mjohnson541 could you investigate what leads to the slow-down?

**Comment by mjohnson541** [comment]
Sorry, I checked it, but I'd seen it timeout that early before on other jobs for no apparent reason.  The slowdown appears to come from calling checkForDuplicates on the edge library.  I should have a fix up soon.

**Pull request merged**
