### PR TITLE
Uncertainty Class Part III: local and correlated analysis

### PR DESCRIPTION
**Pull request by connie**
This pull request is (the possibly last) part of the series relating to the `Uncertainty` class and module (see [Part I](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/749) and [Part II](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/754)). 

- Adds the `Uncertainty.localAnalysis` function which runs local first order uncertainty analysis using sensitivity analysis through RMG's native solver.
- Adds `getPartialUncertainty` function to both `KineticParameterUncertainty` and `ThermoParameterUncertainty` classes, such that we can obtain the partial uncertainty contribution of a rate rule or Benson group within a RMG-estimated kinetic or thermo parameter, respectively.
- Adds correlated uncertainty analysis functionality to both local uncertainty (by toggling `correlated=True` in the `Uncertainty.localAnalysis`  function), or within global analysis (by setting `correlated=True` in the `rmgpy.tools.muq.ReactorModPiece` class before running).
- Adds uncertainty plotting functions to the `rmgpy.tools.plot` module which creates bar plots showing the most influential thermo or kinetic parameters on a user-specified output variable.
- Updates the IPython notebooks `localUncertainty.ipynb` and `globalUncertainty.ipynb` to demonstrate the functionality and explain the methodology in depth.  
- Changes the way the kinetic or thermo parameter uncertainties are assigned. Bill mentioned that they should be added linearly, rather than squared, because the uncertainties have assumed uniform distributions rather than normal distributions. i.e.

image

instead of 

image

### CODE REVIEW

**Comment by KEHANG** [comment]
the reduced PDD model required by`localUncertainty.ipynb` demo is not included in the PR yet

**Comment by connie** [comment]
Ahh I didn't realize that.. Will update this.

**Comment by KEHANG** [comment]
@connie thanks! I saw the added example mechanism. One more question for the muq library, I guess the current status is that linux and mac are fine through anaconda, windows probably still has some issue?

**Comment by connie** [comment]
Yeah, I don't think windows can run it unless somebody makes a package for it.  Also, I think even for linux and mac there are some issues with the conda package such that I don't think it works completely out of the box unless you modify some paths. Since MUQ wasn't written like a typical python program, it just creates some Python .so library files, you have to do some thing to make sure it's on the PYTHONPATH.  So the conda packaging has a hard time with it.  But Bill says it's fine-- people can install it from scratch if they need to.

**Comment by KEHANG** [comment]
@connie I also got `bus error: 10` on Mac (linux is fine), I guess we should re-compile muq binary?

@mliu49 For the` retrieveSaturatedSpeciesFromList` when you don't have a saturated version in the mechanism, since `uncertainty` has already loaded database of the right version, we probably can generate thermo on-the-fly for the desired saturated species.

**Comment by connie** [comment]
Yes, the mac error is known, and I would ignore that for now in terms of the pull request.  

As for the saturated thermo- it seems like most of the time the saturated species is found in the model.  But so far the script hasn't errored on me yet.  The radical species need to use the stable species' thermo before applying the HBI correction, so that's why it uses the saturated species.  It looks like `retrieveSaturatedSpeciesFromList` will just raise an error if it can't find the saturated species for now....

Any plans to merge?

**Comment by KEHANG** [comment]
@connie if so, I guess it's ready to go, I'll go ahead to fix some typo and merge it in soon.

**Pull request merged**
