### PR TITLE
Default binding energies for ThermoDB

### PR DESCRIPTION
**Pull request by davidfarinajr**
### Motivation or Problem
AttributeError: 'ThermoDatabase' object has no attribute 'binding_energies'
https://github.com/ReactionMechanismGenerator/RMG-website/issues/208

### Description of Changes
Use Pt111 binding energies as default.

### CODE REVIEW

**Comment by rwest** [comment]
Thanks David!
This looks like it should work right to me, but I've not actually tried running it.

Did you check if it fixes https://github.com/ReactionMechanismGenerator/RMG-website/issues/208 ?

**Comment by davidfarinajr** [comment]
Not yet, I'm not sure how to test website related things as I haven't done this before 😂.  I think this should work, and the website should function as it did before (using Pt111 as default).  If we wanted to expand website functionality to get/estimate thermo on different metals , we could do this by loading the MetalDB and having some query option to input the metal you want.  If what the user asks for is not in MetalDB, we should then probably default to Pt111.

**Comment by xiaoruiDong** [comment]
@davidfarinajr @rwest I will pull this branch and run it on the RMG dev website (a place to test RMG website at https://rmg.mit.edu:888/). I will test the example mentioned by Dr. West (ReactionMechanismGenerator/RMG-website#208) and let you know when the dev website is ready for further testing.

**Comment by rwest** [comment]
Thanks @xiaoruiDong  - Looks like you've pulled it to the dev website already


Repository | Commit | Date
-- | -- | --
RMG-Py | 8148b5587f85bf3df35c1a4af58277d879afac66load the surface if needed when setting binding energies for ThermoDatabase | Fri, 12 Feb 2021 12:58:27 -0500



Following the `1 result` link from [here on the dev website](https://rmg.mit.edu:888/database/kinetics/results/reactant1=multiplicity%203%0D%0A1%20O%20u1%20p2%20c0%20%7B2,S%7D%0D%0A2%20O%20u1%20p2%20c0%20%7B1,S%7D__reactant2=1%20X%20u0__res=True)

gives a keyerror

```
Environment:


Request Method: GET
Request URL: https://rmg.mit.edu:888/database/kinetics/reaction/reactant1%3Dmultiplicity%203%0A1%20O%20u1%20p2%20c0%20%7B2,S%7D%0A2%20O%20u1%20p2%20c0%20%7B1,S%7D%0A__reactant2%3D1%20X%20u0%20p0%20c0%0A__product1%3Dmultiplicity%202%0A1%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B3,S%7D%0A2%20O%20u1%20p2%20c0%20%7B1,S%7D%0A3%20X%20u0%20p0%20c0%20%7B1,S%7D%0A__res%3DTrue

Django Version: 2.2.5
Python Version: 3.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.staticfiles',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'rmgweb.main',
 'rmgweb.main.templatetags',
 'rmgweb.database',
 'rmgweb.pdep',
 'rmgweb.rmg')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')



Traceback:

File "/opt/anaconda3/envs/rmg_dev/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/opt/anaconda3/envs/rmg_dev/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/opt/anaconda3/envs/rmg_dev/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/rmg/RMG-website/rmgweb/database/views.py" in kineticsData
  2238.             generateSpeciesThermo(reactant, database)

File "/home/rmg/RMG-website/rmgweb/database/tools.py" in generateSpeciesThermo
  364.     species.thermo = database.thermo.get_thermo_data(species)

File "/home/rmg/RMG-Py/rmgpy/data/thermo.py" in get_thermo_data
  1268.                                                               metal_to_scale_to=metal_to_scale_to)

File "/home/rmg/RMG-Py/rmgpy/data/thermo.py" in correct_binding_energy
  1461.             metal_to_scale_from_binding_energies = self.surface['metal'].find_binding_energies(metal_to_scale_from)

Exception Type: KeyError at /database/kinetics/reaction/reactant1=multiplicity 3
1 O u1 p2 c0 {2,S}
2 O u1 p2 c0 {1,S}
__reactant2=1 X u0 p0 c0
__product1=multiplicity 2
1 O u0 p2 c0 {2,S} {3,S}
2 O u1 p2 c0 {1,S}
3 X u0 p0 c0 {1,S}
__res=True
Exception Value: 'metal'

```

**Comment by xiaoruiDong** [comment]
@rwest  Yea, I am currently looking at the error trace and trying to understand if this is an issue due to the database loading of the RMG website.

**Comment by davidfarinajr** [comment]
```
    def load(self, path, libraries=None, depository=True, surface=False):
        """
        Load the thermo database from the given `path` on disk, where `path`
        points to the top-level folder of the thermo database.
        """
        if depository:
            self.load_depository(os.path.join(path, 'depository'))
        else:
            self.depository = {}
        self.load_libraries(os.path.join(path, 'libraries'), libraries)
        self.load_groups(os.path.join(path, 'groups'))
        if surface:
            self.load_surface()
 ```
 We do not load the MetalDB by default, so when we are loading the thermodatabase for website, we might need to set `surface = True`

**Comment by davidfarinajr** [comment]
or just load it by default

**Comment by xiaoruiDong** [comment]
Yes, @davidfarinajr is pointing in the right direction. Currently on RMG-website, instead of calling `database.thermo.load()`, `load_depository`, `load_libraries` and `load groups` are individually called. Therefore, `load_surface()` is missing. I will add it right away.

**Comment by davidfarinajr** [comment]
Thanks!

**Comment by xiaoruiDong** [comment]
@davidfarinajr I also correct the format of the binding energy you added.

**Comment by xiaoruiDong** [comment]
@davidfarinajr Update:[This link](https://rmg.mit.edu:888/database/kinetics/reaction/reactant1=multiplicity%203%0A1%20O%20u1%20p2%20c0%20%7B2,S%7D%0A2%20O%20u1%20p2%20c0%20%7B1,S%7D%0A__reactant2=1%20X%20u0%20p0%20c0%0A__product1=multiplicity%202%0A1%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B3,S%7D%0A2%20O%20u1%20p2%20c0%20%7B1,S%7D%0A3%20X%20u0%20p0%20c0%20%7B1,S%7D%0A__res=True) seems to work now.

**Comment by rwest** [comment]
Except the rate is zero 😂

But I think that's another problem for another day. Probably the website doesn't render sticking coefficients well. 

But it looks like this fixes the original problem and can be merged?

**Comment by xiaoruiDong** [comment]
> Except the rate is zero 😂
> 
> But I think that's another problem for another day. Probably the website doesn't render sticking coefficients well.
> 
> But it looks like this fixes the original problem and can be merged?

I looked into the database, and the original entry is exactly zero (`RMG-database/input/kinetics/libraries/Surface/reactions.py`).

```
entry(
    index = 2,
    label = "O2 + Ni <=> O2X",
    kinetics = StickingCoefficient(
        A = 0.0,
        n = 0,
        Ea=(0, 'J/mol'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    shortDesc = u"""Default""",
    longDesc = u"""Made up""",
	metal = "Ni",
)
```
From my end, I think this PR is okay to be merged.

**Review by rwest — APPROVED** [review]

**Pull request merged**
