### PR TITLE
Update RMG developer install instruction

### PR DESCRIPTION
**Pull request by oscarwumit**
### Motivation or Problem
Run into several problems when doing a clean installation of RMG from source following the instructions recently. Turns out the guidance needs to be updated.  

### Description of Changes
1) set julia version to be 1.8.5, the latest version verified to work with current RMG. Newer julia versions such as 1.9.2 cause issues during compiling. 

2) change the conda backend to classic/default before calling julia command; otherwise compilation won't complete.

3) update julia command so the package installation won't freeze.

### Testing
Did a clean installation with the updated instruction. Ran RMG and Arkane minimal tests and they both work.

### Reviewer Tips
Can try a clean installation to verify the changes.

### CODE REVIEW

**Comment by rwest** [comment]
Please can you put *reasons* for changes into the commit messages?
(A good general habit, not just here)
Thanks!

**Comment by rwest** [comment]
This CI run that on this PR that just failed used 
`julia                     1.8.5                h783901f_0    conda-forge`
The [run on main last night](https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/5818698915/job/15775636913) that succeeded used
`julia                     1.9.2                hb81c242_0    conda-forge`
 
I just created a new environment on my (Intel) Mac (with a new miniconda) and it worked fine with the libmamba solver, and with `julia                     1.9.2                h8d83f4a_0    conda-forge`.

**Comment by oscarwumit** [comment]
Thanks for the comment. I will rebase and update the commit msg.

Regarding the Julia version. Yesterday I did a clean installation of RMG on an ubuntu 23.04 machine following the current instruction. However, using the libmamba solver in the Julia step will cause the installation to stall. I got an error msg saying things like "conda freeze when solving the environment, retrying with classic solver". However, the installation will just stay stalled and won't continue. When I switched to Julia 1.8.5 and used the classic solver, the installation worked fine.

I can try to do another fresh installation of RMG on an ubuntu machine to see if the issue persists.

**Comment by JacksonBurns** [comment]
The issues with Julia 1.9.2 seem to be resolved (see [this successful CI run](https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/5973597214/job/16206162069) using that version), as well as the installation with `mamba` as the solver backend issue. I'll close this for the time being, but if we run into similar issues in the future we can pick this up.

**Pull request closed without merging**
