### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by amarkpayne**
See #1031

### CODE REVIEW

**Comment by KEHANG** [comment]
some documentation files need `COPYING.txt`. A global search of `COPYING.txt` can help identify which files are affected.

**Comment by amarkpayne** [comment]
I only found two documentation files that were affected by this. I have updated them and included the changes in the same commit as the file name change

**Comment by alongd** [comment]
[base.pxd](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/solver/base.pyx), for example, still says
```
Copyright (c) 2002-2010 Prof. William H. Green (whgreen@mit.edu) and the
#   RMG Team (rmg_dev@mit.edu)
```

Is this file different in terms of copyright, or was it overlooked?

**Comment by alongd** [comment]
I see that online it is updated, sorry.
Don't .pxd files automatically update with rebasing?

**Comment by mliu49** [comment]
I just noticed that rmgpy/molecule/adjlist.py did not get updated.

**Comment by amarkpayne** [comment]
I'll take a look at this file and update it. I am thinking of coming up with a way to update these files automatically, so I'll try to put that in one pull request together.

**Pull request merged**
