### PR TITLE
Update anacondaDeveloper.rst

### PR DESCRIPTION
**Pull request by mefuller**
Combine Ubuntu installation commands for gcc, g++, git and make to one line;
add equivalent for installation instruction for Fedora since this is a major distro on the Red Hat side (vs. Debian side of the Linux world with Ubuntu).
This should add clarity for newer users.

### Motivation or Problem
The documentation for the developer install on Linux would benefit from providing instructions specific to Fedora and not just Ubuntu since this is another widely-used distro and serves as a template for most Red Hat derivatives.

### Description of Changes
The necessary command to install gcc, g++, make, and git was added.
Also the four Ubuntu commands were compressed to one line.
Both changes should make installation slightly easier either for those copying and pasting or novice users.

### Testing
The suggested command was executed successfully on a Fedora 32 system.
Installation of multiple packages in one line with apt was confirmed on a current Ubuntu 20.04 system.
These steps have been followed to set up RMG developer environments on Ubuntu 20.04 and Fedora 32.

### Reviewer Tips
Suggestions for verifying that this PR works or other notes for the reviewer.

### CODE REVIEW

**Comment by amarkpayne** [comment]
Sorry for the delay @mefuller . Do you mind squashing the second commit into the first? Otherwise this looks good to me and we can get this in

**Comment by mefuller** [comment]
@amarkpayne I hate to be that guy, but I'm trying to figure out how to squash the commits and I really can't figure out how (and I don't won't to break something) the right way to squash the commit (even with StackOverflow)

**Comment by amarkpayne** [comment]
> @amarkpayne I hate to be that guy, but I'm trying to figure out how to squash the commits and I really can't figure out how (and I don't won't to break something) the right way to squash the commit (even with StackOverflow)

No worries at all! You'll want to type the following commands:
```
git rebase -i master
```
You'll then be sent to a text editor, and you'll see three lines (one for each commit you currently have) that start with "pick". Change the middle one from "pick" to "squash", and the bottom one (which should correspond to the merge commit you just added) and change "pick" to "drop". Then force push the branch.

```
git push -f
```

If this doesn't work I can figure out how to get your one commit in another way, I don't want to trouble you too much.

**Comment by mefuller** [comment]
Replaced with pull request #2020

**Pull request closed without merging**
