### PR TITLE
fix network.__repr__

### PR DESCRIPTION
**Pull request by mjohnson541**
Fixes issue #1300.  Improves handling of arrays in network.__repr__ method and fixes eg5.

### CODE REVIEW

**Comment by goldmanm** [comment]
i think the method also needs modifications for other list variables, shown in #1304. 

Sorry for doubling your work. I thought Alon's comment in #1300 was asking me to look into this.

**Comment by mjohnson541** [comment]
Actually it doesn't, it's only a problem if the quantity is a numpy array.  Lists are fine.

**Comment by mjohnson541** [comment]
That's ok, I figured it out and I figured I'd just put it into a PR.

**Comment by alongd** [comment]
Yes, @goldmanm , I did asked you to look at it. Thanks for both of you for your fixes.
Let's decide on a version to merge.

**Comment by mliu49** [comment]
@mjohnson541 If you could change this to `is not None`, then I think we'll merge this one.

**Comment by alongd** [comment]
#1304 has some more fixes under `__repr__`. @mjohnson541, would you like to adopt them?
Let's agree on the changes and get this merged in so PDep is back to life on master

**Comment by mjohnson541** [comment]
It should be changed to is not None.  @alongd  the other fixes in #1304 are unnecessary only the array variables need to have this change.

**Comment by mliu49** [comment]
Thanks! In terms of merging, I think #1273 should be merged first once it passes. I will rebase and merge this so we don't need to wait for Travis a second time.

**Pull request merged**
