### PR TITLE
Halogens pdep

### PR DESCRIPTION
**Pull request by davidfarinajr**
### Motivation or Problem
This PR makes it possible to run pdep for halogen models.
It is simultaneous with https://github.com/ReactionMechanismGenerator/RMG-database/pull/522 which adds halogens frequency data and groups.

### Description of Changes
1) get statmech data for halogens by skipping over halogen atoms (since the are not treated as center atoms, similar to hydrogen)
2) fixed bug for change in number of freqs removed when a group is removed
3) added support for loading statmech libraries
4) added `energy_correction` to pdep network

### Testing
Was able to get a model running with Pdep for `C=C(F)C(F)(F)F` combustion.

### Reviewer Tips
test pdep model for other types of models.  See if we get same results with new `energy_correction`.

### CODE REVIEW

**Review by hwpang — DISMISSED** [review]
Overall looks good to me, I only a small request

**Comment by davidfarinajr** [comment]
[pdep_test.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/7621159/pdep_test.zip)
I ran ethane oxidation with "modified strong collision" (msc) and "reservoir state" (reservoir) pressure dependence with main/main and halogens_pdep/halogens_pdep RMG-py/RMG-database branches.  The zip file contains the 2 input files, as well as the diff models html between the "main" model and "halogens_pdep" model (between the msc models and reservoir models).  The models are virtually the same although the pdep kinetics are not identical.  Looks like we get one Chebyshev coefficient that differs by 0.0001 (0.6132 vs 0.6133 in this example).  
Screen Shot 2021-11-29 at 4 15 42 PM

**Comment by davidfarinajr** [comment]
I think this PR is ready to go?  @ChrisBNEU tried to run another test between this branch and master, but got an error unrelated to the changes in this PR https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2238

**Review by mazeau — APPROVED** [review]
This looks all good with me and I can't forsee any future issues. Thanks david

**Review by mazeau — APPROVED** [review]
after rebase, still looking good

**Comment by ChrisBNEU** [comment]
[pdep_propene_diff.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/7662827/pdep_propene_diff.zip)
I ran a toy mechanism with propene, due to the error above david mentioned I had to restrict the number of carbons, but I saw similar results to David. Differences with chebychev coefficients between the two branches were on the same order of magnitude.

**Review by ChrisBNEU — APPROVED** [review]

**Pull request merged**
