### PR TITLE
Add LogError to raise LogError for unconverged gaussian log file

### PR DESCRIPTION
**Pull request by hwpang**
### Motivation or Problem
As suggested in #1739

### Description of Changes
Add LogError to raise LogError for unconverged gaussian log file

### testing
didn't test

### CODE REVIEW

**Comment by alongd** [comment]
@hwpang, we'll soon [modify log files in Arkane](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1788), would you like to merge this PR soon to avoid conflicts?

**Comment by hwpang** [comment]
> @hwpang, we'll soon [modify log files in Arkane](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1788), would you like to merge this PR soon to avoid conflicts?

Sorry for the slow response. I was really busy last week. I will address the above comments before this Friday.

**Comment by hwpang** [comment]
> Thanks for this fix, @hwpang !
> Please add a unit test using an errored Gaussian log file.
> While at it, let's raise a similar error in QChem and Molpro Logs. You can find some example crashed jobs [here](https://github.com/ReactionMechanismGenerator/ARC/tree/master/arc/testing/trsh).
> (@dranasinghe, could you add a similar line to Orca?)

I've modified the error message and added a unit test for it.

**Comment by alongd** [comment]
Great, thanks!
Please rebase and squash the fix commits

**Comment by hwpang** [comment]
> Great, thanks!
> Please rebase and squash the fix commits

I've rebased and squashed the fix commit. Thanks for reviewing!

**Comment by hwpang** [comment]
> It all looks good, thanks. Just a minor request: Could you squash the test commit with the commit that added the unconverged Gaussian log file?

These two commits were squashed as requested. Thanks!

**Comment by alongd** [comment]
Perfect! Rebase again?

**Comment by hwpang** [comment]
> Perfect! Rebase again?

I rebased this branch. Thanks!

**Pull request merged**
