### PR TITLE
[Python 3.9] Clar SciPy Re-implementation, `pythoncall` Debugging, Optional RMS

### PR DESCRIPTION
**Pull request by JacksonBurns**
This PR replaces #2623 as discussed in this comment: https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2687#issuecomment-2248623916

### CODE REVIEW

**Comment by xiaoruiDong** [comment]
@xiaoruiDong Mark this PR.

**Comment by JacksonBurns** [comment]
@xiaoruiDong here are the remaining test failures which we should address in this PR.

```
FAILED test/rmgpy/data/solvationTest.py::TestSoluteDatabase::test_saturation_density - AssertionError: assert 1.93 == 0
 +  where 1.93 = round(1.9298279226322848, 2)
 +    where 1.9298279226322848 = abs((6385.1498279226325 - 6383.22))
 +      where 6385.1498279226325 = get_liquid_saturation_density('Hexane', 400)
FAILED test/rmgpy/data/thermoTest.py::TestCyclicThermo::test_add_poly_ring_correction_thermo_data_from_heuristic_using_pyrene - AssertionError: assert 'Benzene' in []
FAILED test/rmgpy/data/thermoTest.py::TestMolecularManipulationInvolvedInThermoEstimation::test_bicyclic_decomposition_for_polyring_using_pyrene - assert [0, 0, 0, 0, 0] == [0, 6, 6, 6, 6]
  At index 1 diff: 0 != 6
  Full diff:
  - [0, 6, 6, 6, 6]
  + [0, 0, 0, 0, 0]
FAILED test/rmgpy/data/kinetics/familyTest.py::TestTreeGeneration::test_f_rules - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (7, 6) + inhomogeneous part.
FAILED test/rmgpy/data/kinetics/familyTest.py::TestTreeGeneration::test_d_regularization_dims - Exception: Unable to calculate free energy for species 'C6H6-5': no thermo or statmech data available.
FAILED test/rmgpy/molecule/moleculeTest.py::TestMolecule::test_count_aromatic_rings - assert [2, 0] == [2, 1, 0]
  At index 1 diff: 0 != 1
  Right contains one more item: 0
  Full diff:
  - [2, 1, 0]
  ?     ---
  + [2, 0]
FAILED test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_naphthyl - assert 2 == 4
 +  where 2 = len([Molecule(smiles="[c]1cccc2ccccc12"), Molecule(smiles="[C]1=C2C=CC=CC2=CC=C1")])
FAILED test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_methyl_napthalene - assert 2 == 4
 +  where 2 = len([Molecule(smiles="Cc1cccc2ccccc12"), Molecule(smiles="CC1=CC=CC2=CC=CC=C12")])
FAILED test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_methyl_phenanthrene - assert 2 == 3
 +  where 2 = len([Molecule(smiles="Cc1cccc2c1ccc1ccccc12"), Molecule(smiles="CC1=CC=CC2=C1C=CC1=CC=CC=C12")])
FAILED test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_methyl_phenanthrene_radical - assert 2 == 9
 +  where 2 = len([Molecule(smiles="[CH2]c1cccc2c1ccc1ccccc12"), Molecule(smiles="[CH2]C1=CC=CC2=C1C=CC1=CC=CC=C12")])
FAILED test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_c13h11_rad - assert 2 == 6
 +  where 2 = len([Molecule(smiles="Cc1ccc([CH]c2ccccc2)cc1"), Molecule(smiles="CC1=CC=C([CH]C2=CC=CC=C2)C=C1")])
FAILED test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_aryne_3_rings - assert 4 == 5
 +  where 4 = len([Molecule(smiles="C1#Cc2c(ccc3ccccc23)C=C1"), Molecule(smiles="C1=C=C2C(=CC=1)C=Cc1ccccc12"), Molecule(smiles="C1#CC2=C(C=C1)C=Cc1ccccc12"), Molecule(smiles="C1#CC2=C(C=C1)C=CC1=C2C=CC=C1")])
FAILED test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_polycyclic_aromatic_with_non_aromatic_ring2 - assert 2 == 4
 +  where 2 = len([Molecule(smiles="C=C1C=Cc2cc3c(ccc4cc5ccccc5cc43)cc2C1=C"), Molecule(smiles="C=C1C=CC2=CC3=C(C=CC4=CC5=CC=CC=C5C=C43)C=C2C1=C")])
FAILED test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_false_negative_polycyclic_aromaticity_perception - assert 2 == 6
 +  where 2 = len([Molecule(smiles="[CH2]c1cccc2ccccc12"), Molecule(smiles="C=C1C=CC=C2C=C[CH]C=C12")])
FAILED test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_false_negative_polycylic_aromaticity_perception2 - assert 6 == 7
 +  where 6 = len([Molecule(smiles="[CH2]C=C1C=CC(=C)c2ccccc21"), Molecule(smiles="[CH2]c1ccc(C=C)c2ccccc12"), Molecule(smiles="C=C[C]1C=CC(=C)c2ccccc21"), Molecule(smiles="C=CC1=C[CH]C(=C)c2ccccc21"), Molecule(smiles="[CH2]C1=CC=C(C=C)c2ccccc21"), Molecule(smiles="[CH2]C=C1C=CC(=C)C2=C1C=CC=C2")])
FAILED test/rmgpy/molecule/resonanceTest.py::ClarTest::test_clar_optimization - ValueError: not enough values to unpack (expected 4, got 2)
FAILED test/rmgpy/molecule/resonanceTest.py::ClarTest::test_phenanthrene - assert 0 == 1
 +  where 0 = len([])
FAILED test/rmgpy/molecule/resonanceTest.py::ClarTest::test_phenalene - assert 0 == 2
 +  where 0 = len([])
FAILED test/rmgpy/molecule/resonanceTest.py::ClarTest::test_corannulene - assert 0 == 5
 +  where 0 = len([])
FAILED test/rmgpy/statmech/ndTorsionsTest.py::TestHinderedRotorClassicalND::test_hindered_rotor_nd - assert 4e-05 == 0
 +  where 4e-05 = round((2.8993250143510827 - 2.899287634962152), 5)
 +    where 2.8993250143510827 = abs(2.8993250143510827)
 +      where 2.8993250143510827 = <bound method HinderedRotorClassicalND.calc_partition_function of Mode(quantum=False)>(300.0)
 +        where <bound method HinderedRotorClassicalND.calc_partition_function of Mode(quantum=False)> = Mode(quantum=False).calc_partition_function
```

There are a couple test failures which look like actual failures to run (`test/rmgpy/data/kinetics/familyTest.py::TestTreeGeneration::test_f_rules` and `test/rmgpy/data/kinetics/familyTest.py::TestTreeGeneration::test_d_regularization_dims`) - the remained run, but produce 'incorrect' results. Some of these might not actually be incorrect, and the tests need updating. Others are likely issues with the reimplemented CLAR optimization. Please let me know how I can help get these running again!

**Comment by JacksonBurns** [comment]
Hi @xiaoruiDong will you be able to work on this PR, or should we re-assign?

**Comment by xiaoruiDong** [comment]
> Hi @xiaoruiDong will you be able to work on this PR, or should we re-assign?

I will work on this but don't have time in a week or two... If this is something urgent, I am ok with re-assignment and can talk to the people who will work on this.

**Comment by JacksonBurns** [comment]
It's not especially urgent - I am going to try and fix some of the failures, but we can continue to chat about it once you have the time!

**Comment by JacksonBurns** [comment]
These are the commits that are specific to the CLAR re-implementation in this PR: https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2694/files/756439fd5096859f3e67002571c0a9e1c19258ff

**Comment by JacksonBurns** [comment]
Command to run the tests related to this PR:
```bash
python-jl -m pytest \
test/rmgpy/data/solvationTest.py::TestSoluteDatabase::test_saturation_density \
test/rmgpy/data/thermoTest.py::TestCyclicThermo::test_add_poly_ring_correction_thermo_data_from_heuristic_using_pyrene \
test/rmgpy/data/thermoTest.py::TestMolecularManipulationInvolvedInThermoEstimation::test_bicyclic_decomposition_for_polyring_using_pyrene \
test/rmgpy/data/kinetics/familyTest.py::TestTreeGeneration::test_f_rules \
test/rmgpy/data/kinetics/familyTest.py::TestTreeGeneration::test_d_regularization_dims \
test/rmgpy/molecule/moleculeTest.py::TestMolecule::test_count_aromatic_rings \
test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_naphthyl \
test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_methyl_napthalene \
test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_methyl_phenanthrene \
test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_methyl_phenanthrene_radical \
test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_c13h11_rad \
test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_aryne_3_rings \
test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_polycyclic_aromatic_with_non_aromatic_ring2 \
test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_false_negative_polycyclic_aromaticity_perception \
test/rmgpy/molecule/resonanceTest.py::ResonanceTest::test_false_negative_polycylic_aromaticity_perception2 \
test/rmgpy/molecule/resonanceTest.py::ClarTest::test_clar_optimization \
test/rmgpy/molecule/resonanceTest.py::ClarTest::test_phenanthrene \
test/rmgpy/molecule/resonanceTest.py::ClarTest::test_phenalene \
test/rmgpy/molecule/resonanceTest.py::ClarTest::test_corannulene \
test/rmgpy/statmech/ndTorsionsTest.py::TestHinderedRotorClassicalND::test_hindered_rotor_nd
```

**Comment by JacksonBurns** [comment]
Didn't work

**Comment by JacksonBurns** [comment]
May need to downgrade julia back to 1.8 or something like that: https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2353#issuecomment-1509939996

**Comment by JacksonBurns** [comment]
@rwest @mjohnson541 I am trying to get the Python 3.9 + `PythonCall` overhaul working - repeatedly running into something like:
```
ERROR: InitError: Python: ImportError: /home/runner/miniconda3/envs/rmg_env/.julia/juliaup/julia-1.9.4+0.x64.linux.gnu/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /home/runner/miniconda3/envs/rmg_env/lib/python3.9/site-packages/rdkit/Chem/../../../../libboost_serialization.so.1.86.0)
```
during test startup. Any ideas?

**Comment by mjohnson541** [comment]
It looks like this issue here: https://discourse.julialang.org/t/glibcxx-version-not-found/82209/7

There's a fix that looks promising a few responses down...they write it in terms of CondaPkg.jl, but if we constrain libstdcxx-ng properly in the environment file it should do the same thing.

**Comment by JacksonBurns** [comment]
Great find, thanks! We actually don't have `libstdcxx` in the environment file because that package only exists for linux (at least, on conda-forge). Any ideas to keep Mac compat?

**Comment by mjohnson541** [comment]
Hmm...possibilities that occur to me: 

1) Build a simple conda metapackage that controls that dependency so it is applied in linux, but not in mac: https://docs.conda.io/projects/conda-build/en/latest/resources/commands/conda-metapackage.html
2) Split the environment file between mac/linux again

**Comment by JacksonBurns** [comment]
Those both seem like good options, will consider once this gets closer to merging.

Latest errors are the same as before (without attempting to limit the library version). I am going to roll in the changes from #2631 and try to get this running without Julia to start with, since I think there is a possible library incompatibility problem with RDKit and SciPy.

**Comment by JacksonBurns** [comment]
TODO: add a pytest mark on all of the tests which require julia and then add a new makefile target or automatic detection in the testing aparatus to allow said tests to fail when julia is not installed

**Comment by JacksonBurns** [comment]
Confirmed that I can now run RMG in plain Python mode with Python 3.9, following the installation instructions as of cce1f4b

**Comment by JacksonBurns** [comment]
Docs build might not need to build Julia stuff anymore

**Comment by JacksonBurns** [comment]
`pydest-xdist` works in pure python mode, so you can run the tests in parallel! :tada:

**Comment by JacksonBurns** [comment]
Need to update graphviz version to the latest

**Comment by JacksonBurns** [comment]
After optimization to get the Clar number, brute force enumerate all structures with that Clar number.

**Comment by JacksonBurns** [comment]
Also, we should not optimize past the most optimal clar structure.

**Comment by JacksonBurns** [comment]
Tweak formulation for this - rather than recursively calling, just add a new constraint that the previous clar number must be met, then stop iterating once infeasible (need to continually copy the molecule?).

**Comment by JacksonBurns** [comment]
Latest commits have successfully re-implemented the solver with SciPy. I will merge this PR now, resolve the few oustanding unit test failures in the base branch, and then work toward adding back Julia and getting this ready to go to main.

**Pull request merged**
