### PR TITLE
Improve flexibility of Molecule and Group drawing algorithms

### PR DESCRIPTION
**Pull request by mliu49**
This PR contains minor refactoring of `MoleculeDrawer` and `Group._repr_png_()` to give more flexibility in creating drawings. The motivation for these changes is to allow the website to display svg images instead of png images.

MoleculeDrawer has been refactored to allow saving to file-like objects, which enables writing the drawing to an HTML response object or a string buffer.

The main drawing algorithm in `Group._repr_png()` has been separated into a new function `Group.draw()` which accepts an additional format argument. `Group._repr_png()` now calls `Group.draw()` with 'png' as the format specifier.

### CODE REVIEW

**Comment by mliu49** [comment]
Ok, between this and the last time I tried to write a rigorous test for group drawing, it's apparent that the graph generated by pydot varies by system. I'll keep trying...

**Comment by mliu49** [comment]
I found a different output format ('canon') that does not include exact position values, so it is consistent regardless of system. The unit test passes Travis now, so I think this pull request is ready to be merged.

**Comment by KEHANG** [comment]
I was testing this branch on windows, and got some error:

```
AssertionError: 'graph G {\r\n\tgraph [dpi=52];\r\n\tnode [label="\\N"];\r\n\t1\
t [fontname=Helvetica,\r\n\t\tfontsize=16,\r\n\t\tlabel="*1 C,Cd,Ct,CO,CS,Cb"];\
r\n\t2\t [fontname=Helvetica,\r\n\t\tfontsize=16,\r\n\t\tlabel="*2 C,Cd,Ct,CO,CS
,Cb"];\r\n\t1 -- 2\t [fontname=Helvetica,\r\n\t\tfontsize=16,\r\n\t\tlabel="S,D,
T,B"];\r\n\t3\t [fontname=Helvetica,\r\n\t\tfontsize=16,\r\n\t\tlabel="*3 C,Cd,C
t,CO,CS,Cb"];\r\n\t2 -- 3\t [fontname=Helvetica,\r\n\t\tfontsize=16,\r\n\t\tlabe
l="S,D,T,B"];\r\n\t4\t [fontname=Helvetica,\r\n\t\tfontsize=16,\r\n\t\tlabel="*4
 C,Cd,Ct,CO,CS,Cb"];\r\n\t3 -- 4\t [fontname=Helvetica,\r\n\t\tfontsize=16,\r\n\
t\tlabel="S,D,T,B"];\r\n}' != 'graph G {\n\tgraph [dpi=52];\n\tnode [label="\\N"
];\n\t1\t [fontname=Helvetica,\n\t\tfontsize=16,\n\t\tlabel="*1 C,Cd,Ct,CO,CS,Cb
"];\n\t2\t [fontname=Helvetica,\n\t\tfontsize=16,\n\t\tlabel="*2 C,Cd,Ct,CO,CS,C
b"];\n\t1 -- 2\t [fontname=Helvetica,\n\t\tfontsize=16,\n\t\tlabel="S,D,T,B"];\n
\t3\t [fontname=Helvetica,\n\t\tfontsize=16,\n\t\tlabel="*3 C,Cd,Ct,CO,CS,Cb"];\
n\t2 -- 3\t [fontname=Helvetica,\n\t\tfontsize=16,\n\t\tlabel="S,D,T,B"];\n\t4\t
 [fontname=Helvetica,\n\t\tfontsize=16,\n\t\tlabel="*4 C,Cd,Ct,CO,CS,Cb"];\n\t3
-- 4\t [fontname=Helvetica,\n\t\tfontsize=16,\n\t\tlabel="S,D,T,B"];\n}'
```

Can you try running test on windows?

**Comment by mliu49** [comment]
Ah, thanks for checking that. I think it's because of different line endings on windows. The output contains `\r\n` instead of just `\n`.

**Comment by KEHANG** [comment]
cool, works now! You can directly git squash and merge into master.

**Pull request merged**
