### PR TITLE
correct barrier for library reactions

### PR DESCRIPTION
**Pull request by davidfarinajr**
### Motivation or Problem
We do not correct the barriers for library reactions.  For some library reactions, the Ea < H0 of reaction with RMG thermo which means the forward rate is too fast and the reverse rate is way way too fast.  This is particularly a problem for the `X + CHX -> HX + CX` in the Deutchmann kinetics library.

### Description of Changes
added an input file option `correct_library_kinetics` (default False) which when turned on, corrects the barriers for library reactions based on the thermo.

Screen Shot 2021-06-25 at 4 01 42 PM

### Testing
Tested this with @mazeau CPOX model, and the barrier for the Deutchmann reaction was corrected.

### CODE REVIEW

**Review by mazeau — DISMISSED** [review]
Yay, this looks great! Thank you very much

**Comment by rwest** [comment]
I still think we should check for which reaction rates this is true and just remove them from our libraries, or stop using those libraries, or fix them. Rather than just quietly altering the barrier (but not the A factor) and hence replacing one dodgy rate estimate with another even dodgier rate estimate (albeit one that is less fast and less prone to cause ODE solver crashes). 

But this looks like it should work as intended, and seems harmless, and will solve some of our problems. But if we're going to keep it then it probably needs documentation (maybe @mazeau could add). 


I suppose one approach would be to build a model with this on but then _check the log files and annotated chemkin files to identify all the reactions it applied to, and go look at them carefully and fix the libraries_.  Maybe that advice could be part of the documentation of this feature.

**Comment by davidfarinajr** [comment]
Does the importer check if Ea >= H0? We might want to check it then. Although I think this is less of an issue for gas phase kinetics, and more of a problem for catalysis, especially if you are using a kinetics library on a different metal/facet with different thermo or a kinetics library from a model that is not thermodynamically consistent (doesn't use thermo to calculate reverse rates). @mazeau compared Deutchmanns thermo to ours and it was very different. We could remove these reactions from libraries, however if our families can't make them, we may have model truncation error. I'd rather have them in there and correct the barriers so that the rates are more sensible so they don't crash the solver.

**Comment by mazeau** [comment]
Does anyone like the idea of keeping the unmolested deutschmann reactions in one direction in one library and then the "fixed" Ea in a separate "adjusted" deutschmann library? That way kids can choose whether they want the OG/as published rates vs the rmg fixed rates?

**Comment by rwest** [comment]
image

**Comment by mazeau** [comment]
will-you-press-the-button-all-of-your-friends-feel-28818188

**Review by mazeau — APPROVED** [review]
this all still looks good, but I think it might not be a good idea to let users easily overwrite their database in case they don't load the correct thermo libraries.

**Pull request closed without merging**
