### PR TITLE
Small catalysis related fixes for website operation

### PR DESCRIPTION
**Pull request by mliu49**
### Motivation or Problem
In order to get the RMG-website working with latest version of RMG. May add additional commits if new issues are discovered.

### Description of Changes
- Set default values for deltaAtomicAdsorptionEnergy when loading the thermo database. Somewhat addresses cfgoldsmith/RMG-Py#76
- Clear atom labels before getting thermo when adding training reactions. Somehow this is only an issue when using `getThermoDataForSurfaceSpecies`. This is likely the problem we were encountering during the catmerge hackathon.
- Add `StickingCoefficient.fitToData` method which is used by the results page of kinetics search. Simply a copy of `Arrhenius.fitToData`.
- Convert Pt back to X when getting element counts from InChI for validating InChI generation.

### Testing
Suggestions for cat examples to run would be appreciated. Also, it would be a good idea to identify a cat example which could be added to RMG-tests (main requirement is completing in less than 4.5 min).

### Reviewer Tips
Make sure tests pass. Should run a catalysis job to make sure functionality is unchanged.

### CODE REVIEW

**Comment by kblondal** [comment]
I pulled the cat_fixes branch, ran the same catalysis job on it that I ran yesterday with the latest master and compared the resulting mechanism files. They have the same number of species and reactions (55 species and 302 reactions in the core, 904 species and 2604 reactions in the edge). The cti mechanism file reactions are the same after taking into account random ordering of products and reactants. The only difference is a very slight difference in thermo for one of the adsorbates – OCHXOX(20) which is estimated by group additivity+ an adsorption correction.

OCHXOX(20) thermo today on cat_fixes:
>         thermo=(NASA([100.00, 2026.73],
>                      [ 5.45124063E+00, -3.77161604E-03,  1.78200747E-05,
>                       -1.16828163E-08,  2.12075825E-12,  1.11085118E+04,
>                       -2.01203746E+01]),
>                 NASA([2026.73, 5000.00],
>                      [ 8.50011069E+00,  1.01262422E-02, -7.20517534E-06,
>                        1.39720743E-09, -9.07220545E-14,  5.78243364E+03,
>                       -4.70738973E+01])))
---
OCHXOX(20) thermo yesterday on master:
>         thermo=(NASA([100.00, 2026.72],
>                      [ 5.45124602E+00, -3.77166220E-03,  1.78201771E-05,
>                       -1.16828946E-08,  2.12077711E-12,  1.11085115E+04,
>                       -2.01203954E+01]),
>                 NASA([2026.72, 5000.00],
>                      [ 8.49941880E+00,  1.01271277E-02, -7.20558476E-06,
>                        1.39728876E-09, -9.07279308E-14,  5.78284921E+03,
>                       -4.70697846E+01])))

But this is so small that I suspect it is a normal fluctuation for estimated thermo?

Otherwise the test indicates that the functionality is unchanged after the fixes.

**Comment by rwest** [comment]
Thanks Katrin. Yes, I think that difference is probably just in the NASA polynomial fitting, so it looks like they're identical to me.

Could you come up with one or two test jobs, like that?
I think these would end up being added (via a pull request) to the RMG-tests repo, like
https://github.com/ReactionMechanismGenerator/RMG-tests/tree/master/tests/rmg

Maybe your catalytic combustion? and/or perhaps one of @mazeau's partial oxidation? As Max says, something that only takes a couple of minutes.

**Comment by kblondal** [comment]
I have created a pull request for a catalytic combustion of methane on platinum example that takes about 3 minutes to run.

... are there any other requirements than the 4.5 min limit?

**Comment by mliu49** [comment]
Thank you for reviewing and testing! I will go ahead an merge this.

**Pull request merged**
