### PR TITLE
Add atom index to Group()._repr_png_

### PR DESCRIPTION
**Pull request by hwpang**
### Description of Changes
Add atom index consistent with adjacency list to molecule group graph for users' convenience.

### CODE REVIEW

**Comment by mliu49** [comment]
Out of curiosity, what happened with the other PR?

**Comment by hwpang** [comment]
> Out of curiosity, what happened with the other PR?

I was testing the PR function in VScode but things didn't work the way I expected lol
Sorry for confusion.

**Comment by mliu49** [comment]
There is a unit test for the Group.draw method which you will need to update.

**Comment by hwpang** [comment]
> There is a unit test for the Group.draw method which you will need to update.

unit test expected result modified

**Comment by mliu49** [comment]
Could you rebase?

**Comment by hwpang** [comment]
> Could you rebase?

Rebase done

**Pull request merged**
