### PR TITLE
Minor: add solvation correction in species.thermo.comment

### PR DESCRIPTION
**Pull request by hwpang**
### Motivation or Problem
I think it would be nice to know if the species's thermo has been corrected with solvation correction of which solvent.

### Description of Changes
I add the solvation correction comment in the attribute species.thermo.comment in the method get_thermo_data() for class Species.

### Testing
Tested locally with benzene as solvant. The result looks like: `Thermo group additivity estimation: group(Cs-CsCsHH) + group(Cs-CsCsHH) + group(Cs-CbCsHH) + group(Cs-CbCsHH) + group(Cb-Cs) + group(Cb-Cs) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + ring(Benzene) + ring(Benzene) + radical(Benzyl_S) + radical(Benzyl_S) Solvation correction with benzene as solvent.`

### CODE REVIEW

**Comment by hwpang** [comment]
> I think this code should be moved to `RMG-Py/rmgpy/thermo/thermoengine.py` after line 89.
> Also, it will be a good idea to add solvation groups in the comment as well. Solvation thermo group can be found in `solute_data.comment`, and `solute_data` is already created in `thermoengine.py`.
> 
> The solvation thermo groups should be separated from regular thermo group in the comment. Maybe it can look something like this?
> `"Thermo group additivity estimation: group(Cs-CsCsHH) + group(Cs-CsCsHH) + group(Cs-CbCsHH) + group(Cs-CbCsHH) + group(Cb-Cs) + ... + Solvation correction with benzene as solvent: (abraham(OssH)+nonacentered(OssH)+abraham(CssH2)+abraham(CssH2)+abraham(CssH3))."`

@yunsiechung Thanks for your comment and review! I think adding the solute data comment into the species thermo comment is a very good idea and will be useful for users. I instead added these at line 71, because I realize that if I added these at line 89, thermo returned in the format of wilhoit at line 80 won't have these comments. I also modified the solvation.py to make the solute data comment slightly prettier.

**Comment by yunsiechung** [comment]
@hwpang Thank you! Everything looks good to me

**Comment by amarkpayne** [comment]
@hwpang have you tested to see if this will break our uncertainty module? Something I want to look into really quick before we merge this in.

**Comment by hwpang** [comment]
> @hwpang have you tested to see if this will break our uncertainty module? Something I want to look into really quick before we merge this in.

@amarkpayne Thanks for your suggestion! I quickly tested it locally with the toy model in examples/rmg/liquid_phase/input.py. I looked the code for parameter source parsing in uncertainty module, which uses the ThermoDatabase method extract_source_from_comments() to parse the source, and it only stores the groups that are existing in the ThermoDatabase attribute self.groups dict for uncertainty assignment. In short, these added commits don't affect the ability of parsing parameter sources for uncertainty module.

I also did the following testing:

(1) Tested find_parameter_sources_and_assign_uncertainties.ipynb: 
-> The comments can be parsed correctly to assign uncertainties.
(2) Added uncertainty block in examples/rmg/liquid_phase/input.py to perform local and global uncertainty analysis: 
-> Local uncertainty analysis results seem normal.
-> Global uncertainty analysis breaks but not because of this PR. Global UA is currently not designed for liquid phase reactor and it requires an P input for sens_conditions, so it breaks for LiquidReactor in general. This can be easily fixed by adding a P = 1e5 kPa for all LiquidReactor global uncertainty analysis, which I'm working on and will push another PR shortly.

**Comment by amarkpayne** [comment]
Thanks for checking @hwpang ! I'll go ahead and merge this in

**Pull request merged**
