### PR TITLE
Halogens transport

### PR DESCRIPTION
**Pull request by davidfarinajr**
This PR replaces https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2098
(have to make a new pull request to remove the hyphen from the branch name)

added halogen corrections to boiling point when estimating critical properties using group additivity
source:https://doi.org/10.1021/ie00008a029

### CODE REVIEW

**Review by rwest — APPROVED** [review]
The original pull request was reviewed and approved. Just waiting for this to pass the automated tests.

**Comment by rwest** [comment]
Hmmm... It should probably be tested.
https://app.codecov.io/gh/ReactionMechanismGenerator/RMG-Py/compare/2114/diff

**Comment by davidfarinajr** [comment]
> Hmmm... It should probably be tested.
> https://app.codecov.io/gh/ReactionMechanismGenerator/RMG-Py/compare/2114/diff

just added unit test for this, and also added `comment` attr for `critical_point`, hopefully that doesn't break anything 😅

**Review by rwest — APPROVED** [review]
Looks good to me.

**Pull request merged**
