### PR TITLE
Add Basic Operations to Scalar Quantities

### PR DESCRIPTION
**Pull request by amarkpayne**
Addresses some of the issues in #903

### CODE REVIEW

**Comment by amarkpayne** [comment]
This PR is now ready for review. In particular if anyone who is familiar with Cython could look over this PR and recommend improvements that would be very much appreciated. 

This PR adds the following features, as discussed at the Code Organization Hackathon:

- Ability to add and subtract scalar quantities. These quantities must have the same dimensions or else an error is thrown. For A + B or A - B, the returned scalar quantity has units of A since it came first.

- Ability to multiply and divide scalar quantities together. In this operation, units are compounded together, and basic simplification is performed (simplifies m**3/m**2 to m, but won't simplify N*m or kcal/J).

- Uncertainties are propogated appropriately for addition, subtraction, division, and multiplication.

- Scalar Quantities can be compared using <,>, ==, !=, =<, =>

- Added method 'has_same_dimensions_as' to check if two scalar quantities have the same dimensions.


Final note: The unit tests added for each of these methods is not reflected in codecov, since we currently are not tracking cythonized code (see #1135).

**Comment by mjohnson541** [comment]
Sorry, I'm a bit backlogged with the aromatic pull requests, but I'll try to get to this one in the next two weeks.

**Comment by mjohnson541** [comment]
My understanding of the new contributor guidelines is that all RMG-Py PR's must not reduce code coverage.  Since this PR reduces code coverage it needs additional unittests.

**Comment by amarkpayne** [comment]
The unit tests added in this PR don't get included in the coverage report since it all deals with cythonized code. Sorry, I should have been more clear.

I checked by inspection to make sure that any code I added was unit tested, but if I need to write another unit test for some code I missed just let me know.

**Comment by goldmanm** [comment]
This looks like an awesome PR. Just a few things we discussed:

1. Fix the multiplicative uncertainty handling
2. Have some way to handle when incompatibilities are created in uncertainty (possibly warn user and make the value `np.nan`)

**Pull request closed without merging**
