### PR TITLE
fix ci reusable workflow to checkout the correct rmg-py

### PR DESCRIPTION
**Pull request by JacksonBurns**
See https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2504#issuecomment-1656372161 and nearby comments - fixes an issue with the CI not correctly checking out RMG-Py from forks.

### CODE REVIEW

**Review by rwest — APPROVED** [review]
Looks right to me - if it works for you!

**Review by rwest — CHANGES_REQUESTED** [review]
Did you only do it in the mac-os job, not the linux? Is that why this still failed?: https://github.com/JacksonBurns/RMG-Py/actions/runs/5697239853/job/15443625949

**Comment by JacksonBurns** [comment]
> Did you only do it in the mac-os job, not the linux? Is that why this still failed?: https://github.com/JacksonBurns/RMG-Py/actions/runs/5697239853/job/15443625949

Yup, thanks for catching that. daecd87 should fix it, but let's have it run for a bit since my brain is apparently full of gravel lately

**Comment by rwest** [comment]
Another thing to consider: what will happen when people *push* to their own fork of RMG-database? 

([🎶 "*Nobody said it was easy...*"](https://youtu.be/RB-RcX5DS5A?t=53) )

**Comment by JacksonBurns** [comment]
I am pushing some changes that will allow the following:
 - calling CI from a branch on RMG/RMG-Py using a branch on RMG/RMG-database
 - calling CI from a fork of RMG-Py using a branch on RMG/RMG-database
 - calling CI from a branch on RMG/RMG-database using a branch RMG/RMG-Py 
 - calling CI from a fork on RMG-Database to a fork on RMG-Py
... I hope

**Comment by JacksonBurns** [comment]
This is much more work than it is worth. Closing this is in favor of just copying the test files over to RMG-database after #2504 is merged here, and eventually just shipping RMG-database with RMG-Py in the same repo.

**Comment by rwest** [comment]
You could forget I mentioned the push to RMG-database. The first two commits of this were probably helpful?
They worked on https://github.com/rwest/RMG-Py/actions/runs/5716129639/job/15486943878 anyway.

**Comment by JacksonBurns** [comment]
#2512 will work on forks without the additional complications as well

**Pull request closed without merging**
