### PR TITLE
Debug library to training script

### PR DESCRIPTION
**Pull request by hwpang**
### Motivation or Problem
I encountered two errors while converting a library containing this Diels-Alder reaction to training reaction. 

(1) Two reactants were wrongly added with the same atom label by `add_atom_labels_for_reaction` because the two reactants are isomorphic.

(2) The A unit caused problem in `add_rules_from_training` because only cm mol s units were expected.

```
Reaction(reactants=[Species(label="ISP", molecule=[Molecule(smiles="C=CC(=C)C")], molecular_weight=(68.117,'amu')), Species(label="ISP", molecule=[Molecule(smiles="C=CC(=C)C")], molecular_weight=(68.117,'amu'))], products=[Species(label="DISP_2", molecule=[Molecule(smiles="C=CC1(C)CCC=C(C)C1")], molecular_weight=(136.234,'amu'))])
```

### Description of Changes
(1) In `add_atom_labels_for_reaction`, I modified such that the labeled_molecule is removed after it is matched to one of the reactant. This way, two reactants won't be matched to the same atom label.

(2) In `kinetics_library_to_training_tools` I added an unit conversion for A from arbitrary unit to cm mol s unit.

### Testing
After the change, the `kinetics_library_to_training.ipynb` can process the library without error.

### CODE REVIEW

**Review by mjohnson541 — DISMISSED** [review]
This looks good to me.

**Comment by mjohnson541** [comment]
Can you rebase?

**Comment by hwpang** [comment]
Thanks for the review! It's rebased!

**Review by mjohnson541 — APPROVED** [review]

**Comment by hwpang** [comment]
I changed '1/s' to 's^-1' for the A unit conversion part to have consistent format with those used in `add_rules_from_training`.

**Comment by hwpang** [comment]
I imported ScalarQuantity from rmgpy.quantity for A unit conversion. Sorry for the multiple follow up changes, this is the last one!

**Comment by hwpang** [comment]
I made some minor changes in the jupyter notebook while preparing for RMG workshop.

- I changed the comment part from 'all' to 'default' because the 'all' option tries to load the Surface families but the relative thermo library is not provided.
- I changed families to list(database.kinetics.famillies.keys()) to allow using 'default' option.

**Review by mjohnson541 — APPROVED** [review]

**Pull request merged**
