### PR TITLE
RMG-database Twin PR: Update to CI

### PR DESCRIPTION
**Pull request by JacksonBurns**
### Motivation or Problem
CI on RMG-database is currently failing because it is out of date, so it is being added over there requiring some changes over here.

### Description of Changes
This PR removes the database tests from CI being run on RMG-Py PRs, and does some minor cleanup.

### Testing
CI run.

### Reviewer Tips
Also see RMG-database PR https://github.com/ReactionMechanismGenerator/RMG-database/pull/635

### CODE REVIEW

**Comment by hwpang** [comment]
Thanks for the PR! This makes me wonder if we would miss bugs in the code that generates the tree, since the code is in `RMG-Py`?

**Comment by hwpang** [comment]
I gave this another think, and I actually think this might be ok. The error in the tree generation code will be detected by the tests [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/test/rmgpy/data/kinetics/familyTest.py#L716). If we can get a second opinion that also ok this then I'm happy to merge. I also just rebased the branch with main.

**Comment by JacksonBurns** [comment]
@hwpang something is missing from the regression testing (like, one of the files appears to be missing), can you tell what it is? It only fails the observable testing.

**Comment by hwpang** [comment]
I rebased this

**Pull request closed without merging**
