### PR TITLE
Some fixes to documentation (and a CI test)

### PR DESCRIPTION
**Pull request by rwest**
### Motivation or Problem
Documentation can be broken without people noticing.
For example [here](http://reactionmechanismgenerator.github.io/RMG-Py/reference/data/entry.html#rmgpy.data.base.Entry) and [here](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2127). 
As suggested in https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2104 we could test the documentation using continuous integration. This PR does that (CI testing) and fixes some of the errors.

### Description of Changes
Pushes to the official master are unchanged: they still build and publish the result, even if it's broken (better something than nothing, being the assumption). Although we now also test the external links for broken or redirected links (this information is just logged).
But pull requests are now built and then tested, but not published. The documentation action should be marked as a failure if there are any warnings. The PR can still be merged, but at least we'll know.  (Also checks and logs broken links).

### Testing
It has been working in deployment. The job is triggered on this PR, and was marked as failing, eg. [here](https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/843271605) until I added commits that cleared up the sphinx warnings, and now it passes.  I have also much reduced the list of broken hyperlinks.
You can find the remaining list by clicking "Details" on the "Build Documentation / build-documentation" check, then expanding the "Check documentation links" step of the log by clicking the ">" arrow.

### Reviewing tips
Look at individual commits. I tried to make them reasonably distinct. If you just look at the overall diff, you'll likely be overwhelmed with a tone of tiny hyperlink changes, and not notice the more significant stuff.

### CODE REVIEW

**Comment by kspieks** [comment]
@rwest Found a few other broken hyperlinks. I corrected some but was unsure what the Arkane manual was supposed to refer to. Feel free to change/squash as needed

**Comment by kspieks** [comment]
Thanks for updating the documentation and for catching some of the documentation I had missed last year when updating Arkane's [ESSAdapter](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/be9c22ed723676fd954b06a429a122c3a47f3ea4). I figured I should complete the documentation now so I added a fixup commit that we can probably squash with your [commit](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2132/commits/8908403cbe5355dd24c71f575bfbc54886917cec). Let me know if you approve.

Since you updated your email, I figured we should update it in all file headers with a simple find replace. 

Otherwise I think this looks good to go so it can be merged soon

**Comment by rwest** [comment]
Thanks for the review, Kevin, and for the additional fixes to Arkane's ESSAdapter documentation. 

Since my old email address continues to work as a forwarding address, I'm not sure it's worth a commit that touches every single file in RMG, and gets entered into the history of changes for them all, resetting all the "last updated" timestamps, etc. 
Although I guess it's only a month since https://github.com/ReactionMechanismGenerator/RMG-Py/commit/40b9dbb9a89ac630dde664020efc16460c54600f so maybe it's not a big deal.

**Comment by kspieks** [comment]
I see. Should we drop the fixup commit for your email? I'm fine either way, especially if both emails work

I fixed my typo on the Arkane commit. Shall I squash it with yours if the documentation tests pass?

**Comment by rwest** [comment]
Thanks Kevin. I dropped the commit that changed my email everywhere, but kept your Arkane ESS one, and merged it.

**Pull request merged**
