### PR TITLE
Fix Failing CI because of `cclib`

### PR DESCRIPTION
**Pull request by JacksonBurns**
### Motivation or Problem
The CI has been failing ([see here](https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/6009736707/job/16299748843#step:4:86)) for a couple days because of the latest release of `cclib` (see [here](https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/5973597214/job/16206162069#step:4:86) for reference), breaking unrelated PRs such as #2533 

### Description of Changes
Disallows `1.8.0` of `cclib` in the RMG `environment.yml`. This is intended as a temporary patch so PRs can keep working and I can do some work locally to find out why this version of `cclib` is failing, and potentially file a bug report with the maintainers.

### Testing
Just using the CI here. As mentioned above, need to do some local debugging to try and find out _why_ this is failing.

### Reviewer Tips
Should be quick to merge (famous last words).

### CODE REVIEW

**Comment by JacksonBurns** [comment]
File diff for the `cclib` 1.8 vs 1.7.2 MOPAC parser class: https://github.com/cclib/cclib/compare/v1.7.2...v1.8#diff-a710fa5d121b2ed984e78fcd7ed5a27924b0cad89d40e34e36d65f8039bc2285

**Review by rwest — APPROVED** [review]
Ok for temporary fix

**Comment by rwest** [comment]
Do we need a tag for "temporary" fixes?  See #2638

**Comment by JacksonBurns** [comment]
I'm more inclined to just open and issue to track the temporary fixes that we should revert with long(er)-term solutions rather than a new label, since I think I tend to pay more attention to the issues personally.

**Pull request merged**
