### PR TITLE
Update example input files with new surface thermo library name.

### PR DESCRIPTION
**Pull request by rwest**
### Motivation or Problem
The example input files for catalysis didn't work.

### Description of Changes
Changed the thermo library name.
Also added a Nickel thermo library to the Nickel example.

### Testing
Examples now run.

### Other notes
A bit worrying this went un-noticed. 
It would be nice to have occasional regression tests that the examples all work. (see #2040)

### CODE REVIEW

**Review by mazeau — COMMENTED** [review]
Looks good but is there a matching database to go with these name changes or were the old names changed but not reflected here? and shouldn't we hold off on using the ni thermo until the metal attributes pr gets merged in?

**Comment by rwest** [comment]
> Looks good but is there a matching database to go with these name changes or were the old names changed but not reflected here? 

Yes, that's the point. [They were changed](https://github.com/ReactionMechanismGenerator/RMG-database/commit/a62905fd6b33bcf321247d1b3a0d325fcb162775#diff-150c67485e6deb6c487a9c1304575d73b8f48c4dcf4c5a68d71dbf0b557af2b8), but the example input files were not brought up to date.

> and shouldn't we hold off on using the ni thermo until the metal attributes pr gets merged in?

You mean because it'll currently be scaled to Ni as if it were on Pt even though it's already Pt?
What will your metal attributes branch do if given this input file? It could be a good test.

**Comment by mazeau** [comment]
> > Looks good but is there a matching database to go with these name changes or were the old names changed but not reflected here?
> 
> Yes, that's the point. [They were changed](https://github.com/ReactionMechanismGenerator/RMG-database/commit/a62905fd6b33bcf321247d1b3a0d325fcb162775#diff-150c67485e6deb6c487a9c1304575d73b8f48c4dcf4c5a68d71dbf0b557af2b8), but the example input files were not brought up to date.
> 

it looks like I forgot to add the 111 there. oops

**Comment by rwest** [comment]
> > and shouldn't we hold off on using the ni thermo until the metal attributes pr gets merged in?
> 
> You mean because it'll currently be scaled to Ni as if it were on Pt even though it's already Pt?
> What will your metal attributes branch do if given this input file? It could be a good test.

Move the second commit (that adds the Nickel library) onto your metal attributes pull request, and get it to work.

**Comment by rwest** [comment]
After cherry-picking the second commit (which adds the Nickel thermo library  to the nickel example file ) to the Metal Attributes pull request #2025, all that's left of this PR turns out to be a duplicate of PR #2017, so I'm closing this PR.

**Pull request closed without merging**
