### PR TITLE
Fix database loading in RMG-Py unit tests

### PR DESCRIPTION
**Pull request by mliu49**
This PR changes database loading in kineticsTest to be done once per class and thermoTest to be done once for the entire module. Warnings about multiple database instances no longer appear.

I was not able to change the loading in kineticsTest to be done once for the entire module because the classes now load different databases. TestReactionDegeneracy loads the actual RMG-database, while TestKineticsParsing loads a toy database located in RMG-Py.

I've also included an old fix for some work-in-progress unit tests in thermoTest so that they work properly, although they still fail. See #887 for more details.

### CODE REVIEW

**Comment by goldmanm** [comment]
I like the usage of the setUpClass / setUpModule for reducing database loading. Do you think this would be beneficial to implement in other unittests too (maybe for another PR)? I am thinking of modifying the kineticsTest to only use disproportionation or creating single-node instances of r-recombination and R_addition_multiple_bond, so that we don't need to load multiple databases or load from training reactions. Do you think adding test-databases & refactoring this method should be part of this PR or a separate one?

**Comment by rwest** [comment]
This is being discussed in a number of pull requests, and so perhaps a comment here is the wrong place, but it just occurred to me: because the database, once loaded, is (often) stored as a module level variable that can be accessed via `import`, we could probably put a `setUp` method in many of these classes that detects if it's already been loaded and only re-loads it if needed. That way, if you run an individual unit test that needs the database, it loads it, but otherwise you could run all the unit tests (kinetics, thermo, diffusion, etc. etc.) and only load the database once. 
Just a thought. (And not intended to delay merging of this particular pull request)

**Comment by mliu49** [comment]
@goldmanm I think changing degeneracyTest to also use the toy database is a good idea. It could probably go in this PR as well.

@rwest I think that's a good idea, but might be a bit challenging to do right now. Since some tests are loading the toy database and others are loading the real database, we would also need to determine which one is the "currently loaded" one.

**Comment by KEHANG** [comment]
@mliu49 @goldmanm is anyone still working on this PR (I guess, only missing piece is to make TestDegeneracy use toy db as suggested)?

**Comment by goldmanm** [comment]
@KEHANG, I'm working on this PR. This will also be adding families to the test_database so I can study some reactions in the class as well.

**Comment by goldmanm** [comment]
@KEHANG, I made the changes which were requested

**Comment by mliu49** [comment]
@goldmanm, do you have more plans for this PR? If not, I think I'll squash the two kineticsTest commits.

**Comment by goldmanm** [comment]
I think it should be ready for code review. We could possibly 
incorporate more unittests into the framework, but then again, that 
could be for another PR.

**Comment by KEHANG** [comment]
@mliu49 @goldmanm I'll review and merge it today.

**Comment by mliu49** [comment]
Let me know when you're done reviewing. I want to rebase and squash before merging.

**Comment by KEHANG** [comment]
@mliu49 It looks good to me. You can prepare the commits and merge it directly.

**Pull request merged**
