### PR TITLE
Fix QM unit tests and Travis build script

### PR DESCRIPTION
**Pull request by rwest**
This should get Travis working again, whether or not you have the encrypted MOPAC license in your travis environment, and fixes a bunch of things in the MOPAC and Gaussian unit tests.

I'm going to try setting up a [mention-bot](https://github.com/facebook/mention-bot) to suggest code reviewers (though I have some ideas of my own).  We can turn it off (organization > settings > webhooks) if it's a pain.

### CODE REVIEW

**Comment by rwest** [comment]
Looks like mention-bot is dead https://github.com/facebook/mention-bot/issues/134 so I nominate @pierrelb or @nickvandewiele

**Comment by nickvandewiele** [comment]
Thanks for this PR.

Some notes:
- I just learned that the word [`licence`](http://grammarist.com/spelling/licence-license/) does exist. :)
- the mopac tests are now skipped on Travis CI whereas previously they were executed.

**Comment by rwest** [comment]
I think the MOPAC tests used to fail when not from the official ReactionMechanismGenerator fork. Now instead they are skipped. I'll try sending this PR from ReactionMechanismGenerator/RMG-Py instead of my own rwest/RMG-Py and see how it behaves.

p.s. do they teach American English in Belgium?  My mnemonic is to think of advice (noun) and advise (verb) which clearly sound different. British English has the same spelling rules for practice/practise and licence/license, although they sound the same. :)

**Comment by rwest** [comment]
As I hoped, MOPAC tests ran when this branch was pushed to ReactionMechanismGenerator official fork: https://travis-ci.org/ReactionMechanismGenerator/RMG-Py/builds/135250709
However, I've just noticed tests I didn't edit in rmgpy/qm/mainTest.py, so I'll add commit's for that before you merge

**Comment by nickvandewiele** [comment]
Yes, the mopac tests completed from a branch on the RMG organization. I will merge this.

**Comment by rwest** [comment]
OK, I think it's ready now @nickvandewiele

**Pull request merged**
