### PR TITLE
Fix `pytest` Discovery Bug (FooTest vs. TestFoo), Add Missing Tests, Fix Generator Tests

### PR DESCRIPTION
**Pull request by rwest**
### Motivation or Problem
Well this is a bit embarrassing. None of us noticed that the unit tests in the classes OutputTest, OutputUnitTest, ArkaneTestThermo, CommonTest, InputTest, Psi4LogTest, QChemLogTest, TeraChemLogTest, ArkaneGaussianLogTest, MolproLogTest, OrcaTest, ArkaneTest, ArkaneKineticsTest, FluxDiagramTest, SimulateTest, DiffModelsTest, GenerateReactionsTest, CanteraTest, RMGToCanteraTest, MergeModelsTest, regressionTest, IsotopesTest, ReactionSystemTest, ResonanceTest, ClarTest, InChITest, AugmentedInChITest, IgnorePrefixTest, ComposeTest, Parse_H_LayerTest, Parse_E_LayerTest, ParseNLayerTest, DecomposeTest, CreateULayerTest, ExpectedLonePairsTest, CreateAugmentedLayersTest, ResetLonePairsTest, FiltrationTest, FindButadieneTest, FindAllylEndWithChargeTest, FindButadieneEndWithChargeTest, ShortestPathTest, DistanceComputingTest, FindAllylDelocalizationPathsTest, FindLonePairMultipleBondPathsTest, RDKitTest, ConverterTest, TranslatorTest, InChIGenerationTest, SMILESGenerationTest, ParsingTest, InChIParsingTest, KekulizeTest, ElementCountTest, PartitionTest, AgglomerateTest, ComboGeneratorTest, SwapTest, were not being discovered or run by pytest, because they don't *start* with the word Test.

### Description of Changes
Maybe we should rename them, but for now lets reconfigure pytest to discover them.

### Testing
Let's see if they show up in the test log. (Maybe some of them will fail)...

### Reviewer Tips
Can anyone think of other ways to check we have got and are running everything?
Did anyone compare the total number of old nose tests and new pytest tests?

### CODE REVIEW

**Comment by rwest** [comment]
Running locally, I get  68 failed, 1788 passed, 26 skipped, 34 deselected, 38 warnings in 617.62s (0:10:17). (But my cythonized binaries may be on a topic branch, so we'll see what the official CI gets.)
If you're up for trying to fix them, @JacksonBurns, I suggest either push to this branch, or else just take the first commit as the start of a new pull request and I'll close this one.

**Comment by JacksonBurns** [comment]
The 'good' thing is that most of the failures were due to incorrect filepaths for files used in testing. Fixing and pushing now.

**Comment by JacksonBurns** [comment]
@rwest should be _mostly_ fixed now. Locally, this was passing all unit tests.

One of the Arkane functional tests is not working anymore, and I don't know why. When running `test_species_atomic_nasa_polynomial` I get an error where the the `statmech` database cannot be loaded when `generate_statmech` calls `get_db`, despite `get_db` very clearly having a case to match `statmech`. I have added a skip to this (for now) since this seems like a global state thing that is more easily fixed by just not using globals rather than debugging this individual test.

**Comment by JacksonBurns** [comment]
Sigh... that worked locally. Going to skip that test too.

**Comment by JacksonBurns** [comment]
Woo for +5% coverage boost. I think this is ready @rwest

**Review by JacksonBurns — DISMISSED** [review]

**Comment by rwest** [comment]
The file test/rmgpy/molecule/isomorphismTest.py is rather confusing. Can you reassure me that it's doing everything intended and not missing any generated tests?

[This](https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/5775533330/job/15653648369) run on the old nosetests contains
```
rmgpy.molecule.isomorphismTest.run_parameter_tests ... ok
distinct multiplicity for both molecules set by user. ... ok
identical multiplicity for both molecules set by user. ... ok
Multiplicity not set for one of two molecules ... ok
Both multiplicities not set. ... ok
rmgpy.molecule.isomorphismTest.test_isomorphism__r ... ok
Testing multiplicities in mol and group that don't match ... ok
Testing multiplicities in group vs. group ... ok
Test isormophism check of a CS group vs. a sulfur containing molecule ... ok
Checks that subgraph isomorphism works with enriched molecules and groups ... ok
Checks isomorphism finds things not isomorphic if given a wrong mapping. ... ok
```

The current pytest has
```
test/rmgpy/molecule/isomorphismTest.py::test_multiplicity_mol_mol_distinct_multiplicity PASSED [ 57%]
test/rmgpy/molecule/isomorphismTest.py::test_multiplicity_mol_mol_identical_multiplicity PASSED [ 57%]
test/rmgpy/molecule/isomorphismTest.py::test_multiplicity_mol_not_specified_mol_specified PASSED [ 57%]
test/rmgpy/molecule/isomorphismTest.py::test_multiplicity_mol_not_specified_mol_not_specified PASSED [ 57%]
test/rmgpy/molecule/isomorphismTest.py::test_isomorphism__r PASSED       [ 57%]
test/rmgpy/molecule/isomorphismTest.py::test_isomorphism_mol_group_not_identical PASSED [ 57%]
test/rmgpy/molecule/isomorphismTest.py::test_isomorphism_group_group PASSED [ 57%]
test/rmgpy/molecule/isomorphismTest.py::test_isomorphism_sulfur_group_sulfur_molecule PASSED [ 57%]
test/rmgpy/molecule/isomorphismTest.py::test_isotope_subgraph_isomorphism_molecule_and_group PASSED [ 57%]
test/rmgpy/molecule/isomorphismTest.py::test_isomorphism_wrong_mapping PASSED [ 57%]
```

the test method names in the latter seem to match up to the test descriptions in the former, apart from the first one which is `rmgpy.molecule.isomorphismTest.run_parameter_tests ... ok` seems to be missing.

Could there be other parameterized and generated tests that we're missing?

**Comment by rwest** [comment]
Here's a thought. Could you check the coverage report of the `test` folder to see if there are any tests not being run?

**Comment by JacksonBurns** [comment]
I have fixed the isomorphism tests (405a76f), found a few more straggler tests (5c46ff6) by including `test` in the coverage report and looking for under-covered test files, and I searched the `test` directory for the `yield` keyword and found no more generator tests. I think this might finally be all of them, but I am waiting to look in the CI logs.

**Review by rwest — COMMENTED** [review]
Thanks. Looks good to me. How confident are you this is all of them? 😆 

(I authored the PR so it won't let me approve it)

**Comment by JacksonBurns** [comment]
> Thanks. Looks good to me. How confident are you this is all of them? 😆
> 
> (I authored the PR so it won't let me approve it)

Reasonably confident - anything else still hiding presumably can't be that destructive.

**Review by JacksonBurns — APPROVED** [review]

**Pull request merged**
