### PR TITLE
Chemkin Mechanism Importer (WIP: rebasing onto RMG3/Python3)

### PR DESCRIPTION
**Pull request by rwest**
_This PR now works!_

### Motivation or Problem
The mechanism importer (on branch `importer`) currently functions, but is based on a version of RMG shortly before the switch to Python 3.   This pull request (from the branch `importer3`) is where we are rebasing and/or copying and/or merging changes to try to make it work with the latest RMG3.

### CODE REVIEW

**Comment by rwest** [comment]
Looks like a problem with `to_adjacency_list`

**Comment by rwest** [comment]
This molecularTermSymbol line will need a fix like https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2054 applying to stop this extra tag being read as a species label

**Comment by JacksonBurns** [comment]
Changing base to main since this seems to be an important change and I need to see how bad the merge conflicts are.

**Comment by JacksonBurns** [comment]
@rwest there are substantial merge conflicts in this PR? Can we close it, or is it worth resolving?

**Pull request closed without merging**
