### PR TITLE
Aromatic Oxygen (and Nitrogen, for that matter)

### PR DESCRIPTION
**Pull request by rwest**
To try and address things like Furans, which should be aromatic, this topic branch (aromaticO) tries
to allow Ob atom types (and hopefully will enable the N3b and N5b atom types to function).
There is still some work to be done, but here is a start. Feel free to add commits to this branch and PR.
- [ ] check the LonePair settings are right on the Ob atom type
- [ ] add the Huckel rule check, in case someone crafts an adjacencylist with 7 Cb's in a cycle? Maybe redundant.
- [x] fix the GroupAtom bugs mentioned below
- [ ] add more, and more granular, unit tests

### CODE REVIEW

**Comment by rwest** [comment]
Currently failing two unit tests:
```python
======================================================================
FAIL: Test the GroupAtom.equivalent() method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwest/Code/RMG-Py/rmgpy/molecule/groupTest.py", line 146, in testEquivalent
    self.assertTrue(atom1.equivalent(atom2), '{0!s} is not equivalent to {1!s}'.format(atom1, atom2))
AssertionError: ['Ob'] is not equivalent to ['O']

======================================================================
FAIL: Test the GroupAtom.isSpecificCaseOf() method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwest/Code/RMG-Py/rmgpy/molecule/groupTest.py", line 174, in testIsSpecificCaseOf
    self.assertTrue(atom1.isSpecificCaseOf(atom2), '{0!s} is not a specific case of {1!s}'.format(atom1, atom2))
AssertionError: ['Ob'] is not a specific case of ['O']
```

**Comment by connie** [comment]
Will it be ok to allow rings more than length 6 to become aromatic?  Do our group contributions account for that correctly?

Also, is this a good time to reorganize atomTypes to be more intuitive and more transparent?  We had talked about perhaps generating the list of atomTypes via a tree.  We could do this as part of the database loading step to initialize the atomTypes.  See previous issues https://github.com/GreenGroup/RMG-Py/issues/283 and https://github.com/GreenGroup/RMG-Py/issues/327

One thing I worry about is what the incrementBond, breakBond, loseLonePair, etc. attributes are used for.  Are they being used to generate groups for detecting the reverse reaction?  What kind of errors can writing these by hand lead to?

**Comment by shamelmerchant** [comment]
Also the b in Cb stands for benzenic Ob as nomenclature might be confusing since it is furanic?

**Comment by rwest** [comment]
I don't know what group contribution database will do. Maybe ring size should be capped at 6?

I agree that #283 is still a good idea.  Was @nickvandewiele working towards it in 75fb7697ebdf95539270b422bdc77b401262d367?
And yes, now may be a good time... But if we can make furan aromatic without having to refactor the entire AtomType mechanism, then I'd rather not wait.  If it turns out we can't, then someone will have to delve in and redo all the AtomTypes.

As for the naming convention...  I don't think there is one that won't cause some confusion. Should the carbon atoms in a furan ring still be called `Cb`? I agree that `Xa` for aromatic may be better than `Xb` for benzenic, but `Oa` is already taken for atomic...  I decided that for now, `b` just means aromatic! We can then check for aromatic rings by insisting every atom type in the ring ends in a 'b' (or 'bf'), for example.

**Comment by mliu49** [comment]
Closing because this is extremely out of date. Aromatic atomtypes for oxygen and nitrogen have been implemented in #1206. However, aromatic resonance structure generation has not been extended to heteroatoms yet. There are other considerations which we will need to think about before taking that step.

**Pull request closed without merging**
