### PR TITLE
Resonance structures of adsorbates don't put radicals on the surface.

### PR DESCRIPTION
**Pull request by rwest**
### Motivation or Problem
See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1820 for details.

Synopsis:  
resonance structure generation was shuffling radicals and double bonds around and ending up with a radical on a surface site `X`.  This adsorbate (with a radical on `X`) then failed to match anything in the adsorption thermochemistry tree and raised a thermo error. 

### Description of Changes
The fix proposed in this PR is: if you try to increment the radical (or lone pair) count on a surface site, it has no effect.
This has a consequence that some resonance structures of an adsorbate have unpaired electrons and some don't. In order for such Species to be passed back and forth through multiprocessing, the `__init__` method of `Species` needed modifying to allow different multiplicities when creating a species; this is only permitted for adsorbates.

### Testing
A few large models with heterogeneous surface chemistry have been run without any errors.
Modified a unit test as needed. Ran unit tests.

### Other
Also includes a couple of small fixes made along the way: one tiny change to make code more readable and fast, and one to improve diagnostic error logging.

### CODE REVIEW

**Comment by mliu49** [comment]
I think the changes themselves look good, and the approach seems to make sense physically. I'm wondering if this has any dangerous consequences.

The first thing that comes to mind is conservation of electrons/multiplicity. If a surface species has one resonance structure with a radical and one without, then you could get what appears to be a radical recombination with a stable species or H abstraction from a radical. I guess it wouldn't matter when simulating though.

Also, would this result in any weird thermo estimates? Since we take the structure with the lowest H298.

**Comment by rwest** [comment]
Some strange things showing up that I don't understand but are quite possibly related to this.

One problem: radical adsorbates still showing up
```
HNOX(541)
multiplicity 2
1 O u0 p2 c0 {2,S} {4,S}
2 N u1 p1 c0 {1,S} {3,S}
3 H u0 p0 c0 {2,S}
4 X u0 p0 c0 {1,S}
```
and a vdW one
```
H2NOX(542)
multiplicity 2
1 O u0 p2 c0 {2,S} {4,S}
2 N u1 p1 c0 {1,S} {3,S}
3 H u0 p0 c0 {2,S}
4 H u0 p0 c0 {1,S}
5 X u0 p0 c0
```
and a biradical vdW adsorbed
```
HNOX(2461)
multiplicity 3
1 O u1 p2 c0 {2,S}
2 N u1 p1 c0 {1,S} {3,S}
3 H u0 p0 c0 {2,S}
4 X u0 p0 c0
```

Another weird thing:
a multiplicity 2 species with no radicals (causes an InvalidAdjacencyListError when you try to load the dictionary)
```
NOX(2818)
multiplicity 2
1 O u0 p2 c0 {2,D}
2 N u0 p1 c0 {1,D} {3,S}
3 X u0 p0 c0 {2,S}
```
that is a duplicate of a species that's already there
```
NOX(507)
1 O u0 p2 c0 {2,D}
2 N u0 p1 c0 {1,D} {3,S}
3 X u0 p0 c0 {2,S}
```

These are copied from the chemkin/species_dictionary.txt file.
(For my own reference: HAN/5ef9a10cc030ff846c80619c3b59eb89d7696912 )

**Comment by rwest** [comment]
Note to self: Gas phase radicals should not adsorb via van-der-Waals.

**Comment by JacksonBurns** [comment]
Changing base and attempting to rebase. Would be nice to get these fixes and tests in, if possible.

**Comment by JacksonBurns** [comment]
@rwest there is a simple conflict to resolve and then this PR can be evaluated for merging. Please resolve if still worth doing, or close otherwise.

**Pull request closed without merging**
