### PR TITLE
Allow the profiling of RMG Jobs that do not converge

### PR DESCRIPTION
**Pull request by rgillis8**
Allows a value wallTime to be read in on the input file. After wallTime lapses the RMG job terminates and profiling data is created.

### CODE REVIEW

**Comment by nickvandewiele** [comment]
so when you specify 00:00:00 should it be interpreted as DD:HH:MM or HH:MM:SS ?

**Comment by rgillis8** [comment]
HH:MM:SS although if the user wrote DD:HH:MM:SS that would also work

**Comment by nickvandewiele** [comment]
Perhaps clarify in the documentation or input file what 00:00:00 means as it could be misinterpreted.

**Comment by rgillis8** [comment]
Sure. It is described in the "commented" input file, but I can also clarify in the attribute description.

**Comment by rgillis8** [comment]
What documentation would I clarify this in?

**Comment by nickvandewiele** [comment]
ok, I missed that. Ignore my comment then.

**Comment by rgillis8** [comment]
Well now that you mentioned this I am seeing that in the RMG object description (in main.py) the wallTime description that was already there doesn't quite match what I've done.

**Comment by rgillis8** [comment]
it says it is a time in seconds when really what was already partially implemented and what I fixed was this HH:MM:SS format which I think is better anyways. I should probably change it? What do you think.

**Comment by nickvandewiele** [comment]
1) I don't see many people wanting to specify a wall clock with a precision up until seconds.
2) I would go for a single supported format DD:HH:MM and not support DD:HH:MM:SS for now.

**Comment by rgillis8** [comment]
Hmm, I think that having seconds precision is important when you are trying to stop at certain steps, especially in short < 5 min jobs. If you were just caring about stopping on long jobs I agree that seconds is pretty silly for a 12 hr job.

**Comment by rgillis8** [comment]
This is ready I think.

**Pull request merged**
