### PR TITLE
Remove Eley-Rideal reactions that involve no gas-phase species 

### PR DESCRIPTION
**Pull request by kblondal**
### Motivation or Problem
Addresses [database issue #448](https://github.com/ReactionMechanismGenerator/RMG-database/issues/448) caused by the reverse Surface_EleyRideal_Addition_Multiple_Bond reaction of a bidentate.

### Description of Changes
Involves hard-coding 'eleyrideal' in family.py and is treated the same way as avoiding desorption of half of a bidentate in reverse adsorption.

### Testing
I tested this on the latest RMG master (database and RMG-Py) for methane catalytic combustion. Before these changes I got the error reported in [issue #448](https://github.com/ReactionMechanismGenerator/RMG-database/issues/448). With these changes, the mechanism generation completed without errors.

### CODE REVIEW

**Comment by Tingchenlee** [comment]
I tried to run the N2 + 3H2 model by using the following branch:
RMG-database: origin/master  and Tingchenlee/ammonia_version2
RMG-Py: surfacedebug(1575c4a335a762c7be2197dc5d0bd3d11c479c00)

The changed solves the issue of the reverse Surface_EleyRideal_Addition_Multiple_Bond reaction of a bidentate. While another problem of the bidentate species came. We had this problem previously:
```
For reaction generation 1 process is used.
Generating thermo for new species...
Error: Could not update atomtypes for this molecule:
multiplicity 1
1 N u1 p0 c0 {2,S} {3,T}
2 N u0 p1 c0 {1,S} {4,D}
3 N u2 p0 c0 {1,T}
4 N u0 p1 c0 {2,D} {5,S}
5 H u0 p0 c0 {4,S}

Error: Error attempting to get thermo for species N=NN(N=[Pt])[Pt](33) with structure 
1 N u0 p1 c0 {2,S} {3,S} {6,S}
2 N u0 p1 c0 {1,S} {4,D}
3 N u0 p1 c0 {1,S} {7,D}
4 N u0 p1 c0 {2,D} {5,S}
5 H u0 p0 c0 {4,S}
6 X u0 p0 c0 {1,S}
7 X u0 p0 c0 {3,D}

Traceback (most recent call last):
  File "/Users/lee.ting/Code/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/Users/lee.ting/Code/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/Users/lee.ting/Code/RMG-Py/rmgpy/rmg/main.py", line 922, in execute
    trimolecular_react=self.trimolecular_react)
  File "/Users/lee.ting/Code/RMG-Py/rmgpy/rmg/model.py", line 614, in enlarge
    self.apply_thermo_to_species(procnum)
  File "/Users/lee.ting/Code/RMG-Py/rmgpy/rmg/model.py", line 824, in apply_thermo_to_species
    self.generate_thermo(spc, rename=True)
  File "/Users/lee.ting/Code/RMG-Py/rmgpy/rmg/model.py", line 831, in generate_thermo
    submit(spc, self.solvent_name)
  File "/Users/lee.ting/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 175, in submit
    spc.thermo = evaluator(spc, solvent_name=solvent_name)
  File "/Users/lee.ting/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 160, in evaluator
    thermo = generate_thermo_data(spc, solvent_name=solvent_name)
  File "/Users/lee.ting/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 125, in generate_thermo_data
    thermo0 = thermodb.get_thermo_data(spc)
  File "/Users/lee.ting/Code/RMG-Py/rmgpy/data/thermo.py", line 1223, in get_thermo_data
    thermo0 = self.get_thermo_data_for_surface_species(species)
  File "/Users/lee.ting/Code/RMG-Py/rmgpy/data/thermo.py", line 1547, in get_thermo_data_for_surface_species
    dummy_molecule.update()
  File "rmgpy/molecule/molecule.py", line 1137, in rmgpy.molecule.molecule.Molecule.update
  File "rmgpy/molecule/molecule.py", line 1362, in rmgpy.molecule.molecule.Molecule.update_atomtypes
  File "rmgpy/molecule/molecule.py", line 1357, in rmgpy.molecule.molecule.Molecule.update_atomtypes
  File "rmgpy/molecule/atomtype.py", line 813, in rmgpy.molecule.atomtype.get_atomtype
  File "rmgpy/molecule/atomtype.py", line 841, in rmgpy.molecule.atomtype.get_atomtype
rmgpy.exceptions.AtomTypeError: Unable to determine atom type for atom N., which has 1 single bonds, 0 double bonds (0 to O, 0 to S, 0 others), 1 triple bonds, 0 quadruple bonds, 0 benzene bonds, 0 lone pairs, and +0 charge.
```
Then I tried cherry-pick the surfacedebug on the debug448 branch, the Nitrogen model was completed. 
How to reproduce:
RMG-database: Tingchenlee/ammonia_version2 (772d146)
RMG-Py: Tingchenlee/debug448 (ca8a911)
Input.py
```python
database(
    thermoLibraries=['surfaceThermoPt111', 'primaryThermoLibrary'],
    reactionLibraries = ['Surface/CPOX_Pt/Deutschmann2006'],  
    seedMechanisms = [],  
    kineticsDepositories = ['training'],
    kineticsFamilies = ['surface','default'],
    kineticsEstimator = 'rate rules',
)

catalystProperties(
    bindingEnergies = {  # default values for Ru(0001)  
    		              'H':(-2.85191775E+00, 'eV/molecule'),
                          'C':(-7.59790076E+00, 'eV/molecule'),
                          'N':(-5.96899731E+00, 'eV/molecule'),
                          'O':(-5.44919557E+00, 'eV/molecule'),
                      },
    surfaceSiteDensity=(2.630E-09, 'mol/cm^2'), 
)

species(
    label='H2',
    reactive=True,
    structure=SMILES("[H][H]"),
)

species(
    label='N2',
    reactive=True,
    structure=SMILES("N#N"),
)

species(
    label='X',
    reactive=True,
    structure=adjacencyList("1 X u0"),
)

surfaceReactor(  
    temperature=(723,'K'),
    initialPressure=(200.0, 'bar'),
    initialGasMoleFractions={
        "H2": 0.67,
        "N2": 0.33,
    },
    initialSurfaceCoverages={
        "X": 1.0,
    },
    surfaceVolumeRatio=(1.e5, 'm^-1'),
    terminationConversion = { "N2":0.80,},
    terminationTime=(0.1, 's'),
)

simulator(
    atol=1e-18,
    rtol=1e-12,
)

model( 
    toleranceKeepInEdge=0.0,
    toleranceMoveToCore=0.0000000001, 
    toleranceInterruptSimulation=1,
    maximumEdgeSpecies=100000,
    minCoreSizeForPrune=150,
    toleranceThermoKeepSpeciesInEdge=0.5, 
    minSpeciesExistIterationsForPrune=4,
)

options(
    units='si',
    saveRestartPeriod=None,
    generateOutputHTML=True,
    generatePlots=True, 
    saveSimulationProfiles=True,
)
```
Another concern is that if I use the debug448 branch and the RMG-database of origin/master, the model created some crazy Nitrogen species (8N, 9N, 10N....), and it took more than 10 hours to finish. 
I'm not sure what's the best way to include the debug448 in the surfacedebug...

**Review by mazeau — APPROVED** [review]
I just tested this using ch4 catalytic combustion (and also using my metal attributes database and rmgpy) and it works! I'm happy with this fix for now, but in the future, I'd ideally like to replace the hard-coded names with a different fix.

**Review by Tingchenlee — APPROVED** [review]
I think I need to focus on how to deal with the database issue in this PR rather than thinking about the thermo error of the N atoms, and yes the change fixed the Eley-Rideal reactions now! Let's merge it!
Thanks, @kblondal !

**Review by rwest — APPROVED** [review]
Lets keep thinking about ways to avoid hard-coding reaction names into RMG-Py as  special cases, but until then this works and is needed, so I approve. Thanks

**Review by amarkpayne — APPROVED** [review]
Looks good to me for now. I agree with the other comments about not hard coding this, but since it is needed now I am fine with merging this in.

**Pull request merged**
