### PR TITLE
added critical_distance_factor parameter to from_xyz/connect_the_dots

### PR DESCRIPTION
**Pull request by davidfarinajr**
### Motivation or Problem
The `from_xyz` method uses the `connect_the_dots` method to create an rmg molecule from arrays of atomic numbers and positions (usually parsed from quantum chem log using cclib).  This method works well for molecules.  However, when I use it for TS geometries, I do not always get a "connected" TS.  For example, for an H Abstraction reaction TS, I sometimes get only one bond for the abstracted H atom.  

### Description of Changes
I created a `critical_distance_factor` parameter for the `from_xyz` and `connect_the_dots` methods.  This parameter had a default value of 0.45, the value we currently use.  Creating this variable allows us to increase the upper bound for the critical bond distance so that we can capture the TS "bonds".

### Testing
sample H Abs TS calculated at M062X/cc-pVTZ with AutoTST
```
import numpy as np
arrays = {'numbers': np.array([9, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1]),
 'positions': np.array([[ 0.015484,  1.417119, -0.24827 ],
        [-0.056923,  0.375352,  0.633999],
        [ 1.043182, -0.58249 ,  0.488915],
        [ 1.922744, -0.566967, -0.505665],
        [-2.36866 , -0.663513, -0.281072],
        [-1.135005, -0.203456,  0.328605],
        [-0.212405,  0.755122,  1.643554],
        [ 1.078201, -1.357264,  1.246945],
        [ 2.697973, -1.315918, -0.577764],
        [ 1.892421,  0.204757, -1.262353],
        [-3.005791, -0.909775,  0.559387],
        [-2.028226, -1.507584, -0.868256],
        [-2.668587,  0.205754, -0.852758]])}
```
sample test code
```
import rmgpy.molecule
TS = rmgpy.molecule.Molecule()
TS.from_xyz(
    arrays["numbers"],
    arrays["positions"],
    critical_distance_factor=0.55,
    raise_atomtype_exception = False
            )
```
Using `critical_distance_factor=0.55` results in "connected TS" while the default 0.45 results in "disconnected TS" (only one bond to abstracting H atom)

### CODE REVIEW

**Comment by davidfarinajr** [comment]
> Can you change this PR so that the branch is coming from this repository instead of your own fork? This will allow the RMG-Tests to run.

Sure @amarkpayne , although I am not sure how to change the branch for this PR.  I have pushed my branch to this repo.  Do I need to open another PR for that branch and reference this PR, or is there a way to change the head branch of this PR?

**Comment by amarkpayne** [comment]
I don't think we have figured out a way to change the branch for the PR, so you might have to open up a new PR for that branch. Just reference this PR from the new PR

**Comment by davidfarinajr** [comment]
Done!  This PR is moved to https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1943.  Sorry about that, I will open up PRs from this repo in the future.  Should we close this one out?

**Comment by amarkpayne** [comment]
Yes, no need to keep it open. I'll close it out right now

**Pull request closed without merging**
