### PR TITLE
make proper `CS` atomType assignment to fix the issue#327

### PR DESCRIPTION
**Pull request by KEHANG**
This PR includes

- adding a new method for identifying sulfur atom

- making `CS` atomType meaningful by defining the condition for `CS` to fix the issue #327 

- adding an unittest for testing `CS` gets properly assigned

### CODE REVIEW

**Comment by nyee** [comment]
I made a fix-up suggestion to make the getAtomType function more concise.  @KEHANG Could just double-check that you think it gives the same output as previously? Other than that, I'm okay with everything else on the commit and I think its ready for pull.

**Comment by KEHANG** [comment]
@nyee Thanks, looks good to me, I'll rebase it and force push to make the history nicer.

**Comment by rwest** [comment]
Before you merge, I have a couple of commits fixing some cython things I'll add to the PR. Probably just a few minutes.

**Comment by rwest** [comment]
If Travis passes, I'm happy to see this merged as is.


I did have an additional optimization, but it causes a cyclic cimport and crashes nastily. @nickvandewiele, how far did you get with that cython book? Any ideas?...
https://github.com/ReactionMechanismGenerator/RMG-Py/compare/CS_thermo...rwest:CS_thermo
```diff
Author: Richard West <r.west@northeastern.edu>
Date:   Sun Jun 12 19:35:29 2016 -0500

    Attempt further cythonization; causes problems.
    
    Add cython declarations for Atom, Bond when counting bonds.
    I think it causes a cyclic cimport.

diff --git a/rmgpy/molecule/atomtype.pxd b/rmgpy/molecule/atomtype.pxd
index be8ca29..d41be48 100644
--- a/rmgpy/molecule/atomtype.pxd
+++ b/rmgpy/molecule/atomtype.pxd
@@ -24,6 +24,8 @@
 #
 ################################################################################
 
+from .molecule cimport Bond, Atom
+
 cdef class AtomType:
 
     cdef public str label
diff --git a/rmgpy/molecule/atomtype.py b/rmgpy/molecule/atomtype.py
index 8a215e1..79053d9 100644
--- a/rmgpy/molecule/atomtype.py
+++ b/rmgpy/molecule/atomtype.py
@@ -327,11 +327,12 @@ def getAtomType(atom, bonds):
     with local bond structure `bonds`, a ``dict`` containing atom-bond pairs.
     """
 
-    cython.declare(atomType=str, atomSymbol=str)
+    cython.declare(atomType=str)
     cython.declare(single=cython.int, double=cython.int, doubleR=cython.int,
                    doubleS=cython.int, doubleO=cython.int, triple=cython.int,
                    benzene=cython.int)
-
+    cython.declare(bond12=Bond, atom2=Atom, atomSymbol=cython.str)
+    
     atomType = ''
     
     # Count numbers of each higher-order bond type
```

**Pull request merged**
