### PR TITLE
refactored Reaction.degeneracy property

### PR DESCRIPTION
**Pull request by goldmanm**
modified the protocol for setting degeneracy to get RMG to update
the kinetics rate constant when degeneracy is changed to keep the degeneracy and
reaction rates in sync.

### CODE REVIEW

**Comment by goldmanm** [comment]
This is just refactoring the code, so I think it doesn't need to be in the Feb 2017 release of RMG, though it is a small pull request and get placed in easily.

**Comment by rwest** [comment]
Are you sure https://github.com/ReactionMechanismGenerator/RMG-Py/pull/911/commits/d6b26cc975f8d1db4ee69110cf53fd6325f73bfc is a good idea? See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/640

**Comment by goldmanm** [comment]
Thanks for the reference, I am sure that d6b26cc is a bad implementation. I am fixing it to make the other classes storing Arrhenius lists to behave like PDepArrhenius already does.

**Comment by goldmanm** [comment]
This PR will be put in the larger degeneracy pull request.

**Pull request closed without merging**
