### PR TITLE
Cantherm Free Rotors, Reduced Moment of Inertia Calculations and bug fix

### PR DESCRIPTION
**Pull request by mjohnson541**
This pull request adds Free Rotors to Cantherm, adds two additional methods of calculating the reduced moment of inertia.  It also fixes a bug where if the HinderedRotor fit is not specified as 'best' the rotor is ignored.  

Based from pull #942.

### CODE REVIEW

**Comment by zjburas** [comment]
This PR addresses 2 fundamental issues in Cantherm related to hindered rotors, which both have demonstrable effects on the output of Cantherm:

1. Treatment of ZPE with hindered rotors (PR #942 )
2. Correct Cartesian coordinate system for Hessian (Issue #981 )

These issues were discovered by comparisons to experiment, and to an analogous software, MESMER.

**Comment by zjburas** [comment]
@rwest , Yes. A more detailed summary will be posted later today.

**Comment by zjburas** [comment]
See detailed explanation at Issue #981

**Comment by mjohnson541** [comment]
This is ready for review, we've already done a number of comparisons available in #981.

**Comment by KEHANG** [comment]
@mjohnson541 I'll review this PR. I did a brief look, seems we don't have any test examples added. I'm sure you guys have some interesting examples during the fixing process, which can be very valuable to prevent future codes breaking this again. After doing that, please also  rebase the branch as well.

**Comment by mjohnson541** [comment]
Oh, I was wondering why you said this needed rebasing, somehow this branch isn't upstream to my local branch and furthermore, when I try to push to this branch I get:
fatal: CanthermRotors cannot be resolved to branch.  

I think it'll be easiest to just close this one and make a new pull request.

**Comment by mjohnson541** [comment]
Replaced by #1040

**Pull request closed without merging**
