### PR TITLE
Elaborating the multiplicity check for nRad = 3 or 4

### PR DESCRIPTION
**Pull request by alongd**
This PR relates to https://github.com/ReactionMechanismGenerator/RMG-Py/issues/965
The multiplicity check was elaborated for up to 4 radicals in a molecule.

### CODE REVIEW

**Comment by goldmanm** [comment]
This looks good to me. I especially like the simplification of `2*nRad/2` to `nRad` and the updated doc string.

**Comment by mliu49** [comment]
Would you like to add a couple of unit tests for molecules with 3 or 4 radicals?

**Comment by alongd** [comment]
I added a test for check_multiplicity.
I was looking for the opposite of assertRaises(), and I understood that simply not asserting anything is the way to go, and in case an error is raised, it will show up.
Let me know if there's a better implementation.

**Comment by mliu49** [comment]
Could you move the test into the `TestConsistencyChecker` class instead of being under `if __name__ == '__main__':`?

I think the best way might be to replicate `test_check_hund_rule_success()` and do
```
try:
    rad1 = ...
except InvalidAdjacencyListError:
    self.fail('InvalidAdjacencyListError thrown unexpectedly for {0}!'.format(rad1))
```
for each of your cases separately.

**Comment by mliu49** [comment]
Ahh, sorry! The code sample I gave doesn't work because if an error is encountered, then you won't be able to use the molecule in the failure message. You can either leave the message as 'InvalidAdjacencyListError thrown unexpectedly!' or add an explicit description of the molecule.

However, that still means that the nitrogen case is raising an InvalidAdjacencyListError for some reason.

**Comment by alongd** [comment]
Thanks for the comments, @mliu49 !
I think this is ready now.

**Pull request merged**
