### PR TITLE
Remove stale template matching for Bimolec hydroperoxide decomposition

### PR DESCRIPTION
**Pull request by hwpang**
### Motivation or Problem
This is a twin PR for RMG-database PR #545.

### Description of Changes
It removes stale template matching code for Bimolec hydroperoxide decomposition.

### CODE REVIEW

**Comment by xiaoruiDong** [comment]
@hwpang Thank you for the change, the RMG-Py part looks good. Can you check the other PR? Thanks
Error: 
image

image

**Comment by xiaoruiDong** [comment]
I think there are issues with generating sample reactions. It requires R(5) to be in a ring, but the sampled molecule is not. For a temporary fix, can you 
1. add the family to the `difficult_families` in the `databaseTest.py` and add a comment nearby about the reason why it is added with mentioning this PR?
2. Raise an issue (if there isn't any related) about potential errors in the accessible test that it may not correctly make molecules with rings?

**Comment by xiaoruiDong** [comment]
@hwpang There is one undetermined kinetics error raised in the RMG-test (attached, other errors in the RMG-tests are irrelevant to this PR). Can you take a look at the change in the RMG-database, and see how this can be fixed? Thanks! Otherwise, I think the RMG-Py PR is ready. You can go ahead and remove the temp PR.

I will merge the twin PRs, after both of them are ready. After you fix the database PR, I will merge that first, and reinitiate the checks in the RMG-Py. I will merge in the RMG-Py PR if necessary checks pass. Thank you again for the effort!

image

**Comment by xiaoruiDong** [comment]
@hwpang, please remove the temporary Github Action commit.

**Comment by hwpang** [comment]
@xiaoruiDong Thanks for the review! I have dropped the github action commit!

**Review by xiaoruiDong — APPROVED** [review]

**Pull request merged**
