### PR TITLE
Make flux diagram work with LiquidReactor

### PR DESCRIPTION
**Pull request by cgrambow**
Removes duplicate code and enables constant species and diffusion-limited rates in `fluxdiagram.py`. Adds additional options to `generateFluxDiagram.py` script to enable functionality mirroring that on the RMG website.

A separate PR is created for the RMG website (ReactionMechanismGenerator/RMG-website#161), because the `createFluxDiagram` function was modified.

### CODE REVIEW

**Comment by mliu49** [comment]
Could you rebase this on master? I'm trying to test this, but I keep running into unrelated errors that have been fixed.

Also, do you have a test case for a liquid example? If you have a small one, it might be good to add as a unit test.

**Comment by cgrambow** [comment]
Rebased and added unit test.

I made the liquid unit test by modifying the simple one to include a constant species and a solvent. The test only checks for the successfully created video at the end, so the accuracy of the chemical system being simulated doesn't matter.

**Comment by cgrambow** [comment]
Done.

**Comment by mliu49** [comment]
Could you rebase this branch? I'll merge it once Travis passes.

**Comment by cgrambow** [comment]
Rebased

**Pull request merged**
