### PR TITLE
Create Cantherm Plot Directory in Output Directory Location

### LINKED ISSUE #1442: Cantherm Plotting Checks Wrong Plot Directory
In RMG-Py/rmgpy/cantherm/thermo.py

Line 252
        if not os.path.exists('plots'):

This line does not correctly check whether if the plots folder exists in the working directory. Instead it checks in RMG-Py

I am running on Windows 7

### PR DESCRIPTION
**Pull request by amarkpayne**
Fixes #1442

This problem was observed in Windows, but likely affects every OS.

### CODE REVIEW

**Comment by alongd** [comment]
Thanks, @amarkpayne!
We have more instances like that in Cantherm, could you add a quick fix to them as well in this PR?
These are:
sensitivity lines [113](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/d07ea878030e71dfd89c8def6f3a568cb2fd9b9e/rmgpy/cantherm/sensitivity.py#L113), [202](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/d07ea878030e71dfd89c8def6f3a568cb2fd9b9e/rmgpy/cantherm/sensitivity.py#L202), [374](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/d07ea878030e71dfd89c8def6f3a568cb2fd9b9e/rmgpy/cantherm/sensitivity.py#L374)
and kinetics lines [303](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/593e9b65de589a94958c647922f92d5c877ba37b/rmgpy/cantherm/kinetics.py#L303), and [320](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/593e9b65de589a94958c647922f92d5c877ba37b/rmgpy/cantherm/kinetics.py#L320)

**Comment by amarkpayne** [comment]
Absolutely! Thanks for finding these.

**Comment by amarkpayne** [comment]
@laitcl tested this, and it seems to work. I have added the fix to all of the other sections as well.

**Comment by alongd** [comment]
Looking good!
BTW, although RMG-tests is probably irrelevant to this PR, would anyone know why they aren't reported here?

**Pull request merged**
