### PR TITLE
Make the Continuous Integration Pass by Default

### PR DESCRIPTION
**Pull request by JacksonBurns**
Right now the regression tests are failing by default - this PR implements the following to fix that:
 - MacOS runners just can't build Julia dependencies, so only the ability to solve the environment and build RMG, then exit
 - Regression tests are considered 'passing' if they execute at all, the actual comparison will be written to the PR by a bot for manual review by humans

### CODE REVIEW

**Comment by ChrisBNEU** [comment]
This looks good, really like the bot. I might have missed it but do we know why the MacOS runners can't build the julia dependencies?

**Comment by JacksonBurns** [comment]
> This looks good, really like the bot. I might have missed it but do we know why the MacOS runners can't build the julia dependencies?

Thanks! See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2453 TL;DR: the GitHub runners just don't seem up to the task.

**Review by ChrisBNEU — DISMISSED** [review]
This looks good to me! Thanks putting the PR together.

**Comment by rwest** [comment]
The `exit 0` for the MacOS doesn't seem to do what's intended.

In this run https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/5590577981/jobs/10220474560 the mac runner carried on to the julia step, timed out, and failed (thus killing the ubuntu run).

And in this run https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/5590578639/jobs/10220475578 the mac runner is still going.

**Comment by JacksonBurns** [comment]
Ah, I had done this differently on a previous commit [like this](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/5ddc6521156c05a63265877fafe6c909c74ff929) and then changed it to this hoping it would work. Fixing now.

**Comment by mjohnson541** [comment]
I like it! Looks good to me!

**Comment by rwest** [comment]
I merged this, so that we can get all the other pull requests to use it, but I can think of a couple of further improvemenst.
1. the Regression Test results are split between the "Regression Tests - Compare to Baseline" output in the job runner log (eg. [here](https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/5592025019/jobs/10223920519)) that I think nobody will now ever look at, and the current annotation which in fact has a bunch more detail than is often needed. Would be nicer if the type of summary that's currently in the job logs ended up in the annotation.
2. the mac runner *sometimes* succeeds at doing julia step. It might be nice to distinguish between a time-out (github computers not up to the task) and a failure (because something has changed in our install stack and things are actually broken for MacOS). i.e. we could let the MacOS runner *try* the julia steps, but accept a time-out as a "pass".

**Pull request merged**
