### PR TITLE
Twin RP for merged all 2+2 cycloaddition families

### PR DESCRIPTION
**Pull request by hwpang**
### Motivation or Problem
This is a twin PR for "merged all 2+2 cycloaddition families PR in RMG-database" to pass mainTest.

### Description of Changes
1. Updated all folder in rmgpy/rmg/test_data/restartTest/seed_w_filters/ since they contain the old 2+2_cycloaddition families. I commented out reatartFromSeed in restart_w_filters.py, reran the RMG job, and copied & pasted the new seed, seed_edge, and filter.

2. Put 2+2_cycloaddition to the generated_trees list.

### Testing
After the changes, "merged all 2+2 cycloaddition families PR in RMG-database" can pass mainTest locally.

### CODE REVIEW

**Comment by hwpang** [comment]
The last force push rebased this PR, which removed the first commit due to a recently merged PR that uses the autoGenerated flag instead of the hard-coded list.

**Comment by hwpang** [comment]
@mjohnson541 Rebased & all tests have passed!

**Comment by mjohnson541** [comment]
I think this needs rebased after the merge done last night.

**Comment by mjohnson541** [comment]
Or, but I guess I need to remove the commit anyway

**Comment by mjohnson541** [comment]
Actually I can't see RMG-tests for the combined PRs, which is important with these changes, can you rebase both of them?

**Comment by hwpang** [comment]
@mjohnson541 Both are rebased!

**Pull request merged**
