### PR TITLE
print out reverse rates in cantherm kinetics jobs

### PR DESCRIPTION
**Pull request by mjohnson541**
Causes the equilibrium constant and reverse rate coefficients to be printed out along with the forward rate coefficients in a Cantherm kinetics job.

### CODE REVIEW

**Comment by goldmanm** [comment]
what files exactly are being modified? Is it just adding to the comments or is a machine-readable Arrhenius form output?

I'm not implying changing it. Just want clarification.

**Comment by mjohnson541** [comment]
It was just adding comments-putting the Keq(T) and krev(T) values in a table, I'm not sure how useful machine readable Arrhenius would be, but now that you mention it, I think at least providing an Arrhenius fit of the data for kf and krev would be helpful.  I'll add that.

**Comment by mjohnson541** [comment]
I just added a commit to print comments with Arrhenius fits for reverse rate coefficients with and without tunneling.

**Comment by goldmanm** [comment]
Looks great @mjohnson541. Thanks for the reminder about reviewing.

**Pull request merged**
