### PR TITLE
Add unittest to make sure Cd atomtype used correctly.

### PR DESCRIPTION
**Pull request by nyee**
This adds a unittest for making sure Cd atoms are used correctly. This new test should be failing in Travis until the analogous (and much larger) pull request for database is merged

### CODE REVIEW

**Comment by nickvandewiele** [comment]
The travis build failed:

The command in .travis.yml:

```
yes 'Yes' | $CONDA_ENV_PATH/bin/mopac $MOPACKEY > /dev/null
```

results in the following error:

```
/home/travis/build.sh: line 45: /bin/mopac: No such file or directory
```

So for some reason `$CONDA_ENV_PATH` evaluated to an empty value.

**Comment by nickvandewiele** [comment]
I see this error also for previous builds of branches.

**Comment by nickvandewiele** [comment]
The variable `CONDA_ENV_PATH` previously existed when you activated a conda environment:
`source activate rmg_env`. Now it doesn't anymore.

**Comment by nyee** [comment]
Any idea why? That commit doesn't change anything having to do with conda enviornments. Only three files changed, two of which are documentation rsts. That can't have anything to do with it can it?

**Comment by nickvandewiele** [comment]
The `yes 'Yes' | $CONDA_ENV_PATH/bin/mopac $MOPACKEY > /dev/null` command appears in the `install` section of the .travis yaml because it needs to access the encrypted `MOPACKEY` environment variable.

I am unsure if it is possible to move that command to a location more downstream that prevents it crashing everything after that, like it does now.

**Comment by nickvandewiele** [comment]
It seems like the conda folks are trying to get rid of that variable: https://github.com/conda/conda-env/issues/197

**Comment by nickvandewiele** [comment]
We chose to use the latest version of miniconda [here](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/ee17af3702baa66ba15a42817a207a9048c59dda), because the `2.2.2` version crashed.

https://github.com/ReactionMechanismGenerator/RMG-Py/pull/667

**Comment by connie** [comment]
We can probably replace `$CONDA_ENV_PATH` with `$HOME/miniconda/envs/rmg_env/` for now.

**Comment by nickvandewiele** [comment]
yep, seems to work.

**Pull request merged**
